### ISSUE TITLE
"End Secure Session" doesn't always end secure session

### ISSUE THREAD

**Issue by Fuzion24** [WhisperSystems/TextSecure#1308]
Sometimes the app continues to send encrypted messages after attempting to end the secure session.

**Comment by wp9015362** [comment]
> moxie0 commented on 7 Apr 2014
>
> Personally, I'd like to eliminate the option all together.
> This is a great example of something that, regardless of what we name it,
> users don't (and shouldn't!) need to understand.

+1

**Comment by moxie0** [comment]
@wp9015362 Keep doing this and we'll ban you from the repo.

**Comment by wp9015362** [comment]
@moxie0 :

I basically just did the same thing as:

https://github.com/WhisperSystems/TextSecure/issues/1308#issuecomment-39706942
https://github.com/WhisperSystems/TextSecure/issues/1308#issuecomment-39755700

That's all.

Can you tell me why I can't do what they did?

**Comment by ApolloLV** [comment]
The Option is still placed pretty prominently in the UI, which lead me here (Because I wanted to know what it does). I would suggest hiding it way lower in the settings with something like "End all secure Sessions" for users experiencing problems. That way, no one will be irritated by the option, while it stays accessible for specific use cases.

**Comment by jeremymasters** [comment]
I actually had this option come in handy a couple weeks ago when the session with my mom went wacky.  This solved the issue and it hasn't returned. Yes, I have my mom using TS. :smile:

**Comment by wp9015362** [comment]
> @moxie0 wrote:
> 
> Personally, I'd like to eliminate the option all together.
> This is a great example of something that, regardless of what we name it,
> users don't (and shouldn't!) need to understand.

Could you please eliminate the "End secure session" option now?

I still don't know what it actually does and when to use it and when not.

Also, from reading the comments here, it might have had to do something with encrypted SMS?

So, since the encrypted SMS feature has been removed, the option could be removed as well?

And if you won't remove the option (for whatever reason) then could you please at least explain the option somewhere? Like in the Wiki for example:

https://github.com/WhisperSystems/TextSecure/wiki/Using-TextSecure

?

**Comment by moxie0** [comment]
@wp9015362 Please only post when you have new information to add.

**Comment by rhodey** [comment]
@moxie0 closed #3055 earlier today, it follows that this should also be closed. end secure session does indeed end the session, the vocabulary could maybe be improved though.
