### ISSUE TITLE
Does not always notify for MMS

### ISSUE THREAD

**Issue by robertpicciotti** [WhisperSystems/TextSecure#1429]
When an MMS is received, it is not always automatically downloaded. Furthermore, sometimes the phone gives no notification the MMS was received.

**Comment by rhodey** [comment]
this issue is crazy old and our MMS code has changed many times over since, unfortunately all information in this issue is stale & cannot benefit us in improving MMS further. if anyone in this thread is still having issues with MMS please find a recent issue that matches your behavior and preferably network provider and add a debug log there.
