### ISSUE TITLE
Queue data messages

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#1654]
At the moment sending of data messages fails if there is no internet connection. You are able to choose SMS fallback. I think it would be good to start queueing the message and send it when the internet connection is established again. We could add a little notice to the dialog which pops up when you tap the message for fallback. Something like: "Your message will be sent when you have a internet connection again. If you don't want to wait, you can send a SMS now"

What do you think?

*edit: posted it in the mailing list now*

**Comment by moxie0** [comment]
This will resolve itself when we get rid of encrypted SMS.

**Comment by midi** [comment]
The behaviour now is better, but I would really like to see messages being queued until a network connection is available.

Currently I sometimes find myself writing messages when I don't have a data connection available and instead of the error message after a while, having TextSecure send the message once a data connection is available would be wonderful. Having to remember to try to re-send after the data connection is back is cumbersome.

For reference, other data based messengers such as Whatsapp and Telegram handle this gracefully and don't time out for me.

**Comment by agrajaghh** [comment]
@midi I have no problem with that. Sending a message while in airplane mode e.g., it will be sent after the netwrok connection is back... Or are you talking about sms?

**Comment by moxie0** [comment]
@midi That's how it works.  Messages will only fail after the device reports that a network is available, and TS has tried (and failed) to send 20 times.  While the network is unavailable, TS will queue the message.

**Comment by midi** [comment]
@agrajaghh 
Talking about data messages of course.
For how long?
@moxie0 
How long is 20 times in measurable time?

This happens to me quite frequently, like in the subway, today again actually. I have some time to read and reply to messages but either no network connection or no data connection or a data connection but so overloaded that nothing gets through.
I'm curious what the other messengers do differently.
Because they handle my and my network connections just fine, Email too obviously.

**Comment by moxie0** [comment]
@midi However long it takes.

**Comment by generalmanager** [comment]
@moxie0 What are the reasons not to try more often (say 100 times)? Is there a delay between the retries?
