### ISSUE TITLE
Automatic backup

### ISSUE THREAD

**Issue by pguth** [WhisperSystems/TextSecure#1876]
With regards to #1705 I would propose automatic daily backups.

There things to consider: If a person has not set up a passphrase, would an automatic backup be of security concerns? That would introduce the need for another UI-element, which is not an option when sticking to the development ideology. And only having automatic backups after setting up a passhprase is opaque.

So I guess the best solution would be to bring in Flock: Let's enable automatic backups only if Flock is present and in a way that only Flock can access the (maybe unsecured) backup-data.

**Comment by phipolis** [comment]
Riffing on the idea of backing up to Flock:

One difficulty of this proposal may be in paying for it. Flock's model of asking $5/year covers the servers and storage to host an average user's contacts and calendars. I have no idea the margins in size and bandwidth this implies, but I strongly suspect it would be dwarfed by a few years of an average user's message history. In addition to the reams of text, there is the even greater multiplier of images / other multimedia content.

I second really liking the idea of Flock integration. A good starting point might be automatic backups of TextSecure's (and RedPhone's) key material. Then first run could ask if the user has used Flock before, directing them to install/login rather than generating a new key.

**Comment by rhodey** [comment]
closing as duplicate of #339
