### ISSUE TITLE
Please remove the "nag screen" asking me to use push instead of SMS

### ISSUE THREAD

**Issue by user-2** [WhisperSystems/TextSecure#1891]
I am using SMS on purpose because I have found it to be more reliable than push on my phone's network. I keep getting a text secure nag screen popup asking me to use push. Please remove this nag screen completely, or add a checkbox to permanently hide it. I appreciate all of the hard work put into text secure, but users shouldn't be nagged to use push.

**Comment by creolis** [comment]
I'm not happy that SMS support is being dropped since this is why I use this app. Internet based message transfer is available via other tools like Threema, Telegram, .. you name them. OTR over SMS is the thing that brought me here. Hopefully someone will fork as soon as SMS support is dropped.

As for the nag screen: If I dismiss the nag note I chose to do so. It's EXTREMELY inconvenient that it returns after a while. Either remove the "X" that dismisses it, or permanently hide it if I chose to :-)
