### ISSUE TITLE
SMS larger than 160 fail to send (CDMA)

### ISSUE THREAD

**Issue by arteuzeander** [WhisperSystems/TextSecure#191]
App will not send SMS when longer than 160 characters  (max possible on CDMA networks).  App should split and send as multiple messages.  I'm using CM7 (gingerbread) ROM on HTC Merge.  Please fix this.

**Comment by rhodey** [comment]
this issue contains no debug logs and is crazy old, will reopen if we can get a debug log and confirmation that it is still occurring, haven't seen any hints of this recently though.

**Comment by Neob91** [comment]
I'm experiencing this on One Plus 3 with Nougat. Also experienced it with Nexus 5 with Marshmallow. Only occurring with the Messenger app, it's fine with Hangouts.

**Comment by hauntingEcho** [comment]
My mom is experiencing this on a Galaxy s7 with US Cellular (working on sending a debug log but connection is spotty where we're at)

**Comment by hauntingEcho** [comment]
https://debuglogs.org/9622cb9c7b0a684618c78f8dc9d240d62b14163b377fe8a758bd3163f07ae35a

**Comment by pcttech** [comment]
This issue may be old, but it has been present for years on the US Cellular network and continues to affect devices. I believe the crux of the issue is that US Cellular does not support concatenated SMS, as hinted at by [this Twilio post](https://support.twilio.com/hc/en-us/articles/223181508-Does-Twilio-support-concatenated-SMS-messages-or-messages-over-160-characters-). For the record, _all apps_ I've tried that attempt to send multi-part messages / concatenated SMS experience this failure. The only apps that succeed are ones that convert to MMS, like Android Messages or the stock Messaging apps.

Although I do not believe this bug to be necessarily Signal's "fault," it would be nice if a workaround could be implemented to allow the sending of long messages as MMS for those who use the US Cellular network.

Here's one of the relevant debug lines:
`D RilRequest: [5621]< RIL_REQUEST_CDMA_SEND_SMS error: com.android.internal.telephony.CommandException: SMS_FAIL_RETRY ret={ mMessageRef = 108, mErrorCode = 100, mAckPdu = null}`

And here's a log:
[Signal SMS Send Failed Relevant Logs 20190618.log](https://github.com/signalapp/Signal-Android/files/3303239/Signal.SMS.Send.Failed.Relevant.Logs.20190618.log)

This issue is highly reproducible. Let me know if I can help.
![Screenshot_2019-06-18-12-15-56 (2)](https://user-images.githubusercontent.com/51971784/59717022-fcf7d600-91cb-11e9-915c-76c56ab22c7c.png)
