### ISSUE TITLE
Push messages are not sent/received

### ISSUE THREAD

**Issue by openpaul** [WhisperSystems/TextSecure#1971]
I use TS quite frequently with a lot of people. But sometimes some people do not get my messages.
often I can re register for push-messages and it will work again. Still it will break some other conversations and soon I'll have the same issue again.
I am using TS 2.1.8 on Android 4.2.2
I think there should be a feature to see if the other person received the message or it should be more reliable.

great app anyhow.

same bug here: http://support.whispersystems.org/customer/portal/questions/6354161-push-messages-are-not-sent-received

**Comment by devurandom** [comment]
Copying my issue description from #2293:

> Currently message delivery is unreliable. It often happens that I send a message to someone, but do not get a message receipt (check-mark icon). Messages sent later get a receipt. When I talk to the person a few hours later, they tell me they did not receive the message.
>
> This issue is not limited to me sending, but also happens the other way around. It also happens for other people, as I have been told. It also happens for the message receipts themselves – sometimes a message arrives on my phone, but the sender never receives the receipt. The CyanogenMod integrated WhisperPush service is not involved. The issue happens between stock Android users, as well as with CyanogenMod users.
>
> From reading other issues I understand that GCM does not offer reliable delivery. I wonder if the equivalent of XEP-0198 section 4 "Acks" could be implemented on top of it in TextSecure.
>
> Possible duplicates: #679, #970, #1971, #2098, #2238

**Comment by moxie0** [comment]
@devurandom Stop it. That is not helpful.

**Comment by manhole11** [comment]
It IS helpful. He's trying to reach as many users as possible of his problems, so we know we're not alone.
Instead of saying it's not helpful, what helpful thing can we do? Are you aware of the problem? Is anyone working on a fix? Why don't you say anything? You guys at whispersystems (only the android team, actually) have a terrible attitude towards bugs.

**Comment by devurandom** [comment]
As for my reasons: The intention was not spamming for attention, but me being convinced that there are several duplicates of this issue. My own duplicate was closed for the obvious reason, but without a hint which other bug is the one "main" bugreport you are going to communicate through. Thus I tried to preserve my assessment on the symptoms and the information about the potential duplicates, which I found during my rather exhaustive research (wading through pages long reports to decide whether the reporter experienced the same issue as I am), so that other reporters would have it easier.

And while @manhole11 might be right that communication might be lacking sometimes, I am quite glad that often my reports (here or via Google Play) were fixed quite quickly. So thank you for that!

Anyway, I think we should not any further derail the discussion into non-technical issues.

**Comment by LikeHoo** [comment]
Well, I think this should really be a high priority issue. I'm using ts with about 30 collegues for quite a long time, but sending messages between 5pm and 8pm (GMT+1) results in 80% loss of messages or delay of 1 hour or more.
If this problem is caused by google cloud messaging service (high server load?) then another service for message delivery sould be used.

**Comment by tzaeschke** [comment]
@LikeHoo +1, same here (Switzerland)
As 'LikeHoo' said, if this is due to google's GCM, then it should be replaced.

**Comment by manhole11** [comment]
Agreed, this should be a very high priority issue. I too have quite a few contacts and most of them are non-techie, it's hard to explain them that gcm is the problem. To them, if TS doesn't send/receive messages, TS sucks and must be ditched.

**Comment by midi** [comment]
Had this happen yesterday again.
Contact was getting the feeling that I might not have gotten the last message, she was right.

I'm starting to see, that this creates a uncomfortable feelings for my contacts, because they don't know if I have really received the message.
For me, as it is now, I can only use Textsecure with people who are aware of these reliability problems.

Some contacts I have sporadic communication. To miss out on one of these sporadic messages would be horrible.
I got my close circle to switch to Textsecure and Redphone, but as it is right now, I'll have to switch over to Whatsapp, that I reluctantly started using.

I do cherish Redphone/Textsecure and the upcoming (finally) Signal suite. Unfortunately I have spent so much time in explaining, trouble shooting, being angry because of missed messages, disconnects, that it looks like an utopian dream right now.

If there's anything I can do to help making it more reliable, I have a lot of experience using Textsecure/Redphone with partners, on VPN, crappy connections and number changes, device changes, crashes, bla blah...
Tell me what can be done. Getting logs from my conversation partners might be complicated, but I have a few that I could direct to provide them.

Cheers

**Comment by manhole11** [comment]
That is exactly how I feel. Too much time spent troubleshooting, TextSecure just isn't ready for the average user, whatever the developers say. When I hear people talk about TS like a tool with "simple, invisible-to-the-user encryption that just works", I always think "just wait a couple of days".

**Comment by gordon-morehouse** [comment]
Added detailed description of push message delays (does not apply to SMS transport) at #2238. And I agree with the above users who are trying to coordinate a single bug in which to discuss this. It's helpful. I suggest #2238.

**Comment by gordon-morehouse** [comment]
I've added a detailed report of my issues with push messages in #2238.

I agree with the users who are attempting to wrangle a canonical bug report in which to discuss this. Doing so is helpful. I recommend #2238.

**Comment by rhodey** [comment]
this issue was opened before delivery receipts, with the advent of delivery receipts and a bunch of other things I'm going to close this issue as crazy-stale. we still have some issues open related to delivery and receipt of push messages but they contain more recent debug logs and relevant information. If you've still experiencing and issue with message delivery & receipt please chose an existing issue and add what you can to it.
