### ISSUE TITLE
Group MMS in text secure

### ISSUE THREAD

**Issue by Techmo-906** [WhisperSystems/TextSecure#2013]
I can get group MMS messages but I cannot reply to any it just bounces back undelivered. SMS messages I can send just fine but I cannot do mms group messages.

**Comment by rhodey** [comment]
this issue is crazy old and our MMS code has changed many times over since, unfortunately all information in this issue is stale & cannot benefit us in improving MMS further. if anyone in this thread is still having issues with MMS please find a recent issue that matches your behavior and preferably network provider and add a debug log there.
