### ISSUE TITLE
MMS issues

### ISSUE THREAD

**Issue by karlhedderich** [WhisperSystems/TextSecure#2058]
I am not receiving group messages seemingly randomly.  I will receive some but not others.  I know this is happening for some of my friends that are using textsecure. http://hastebin.com/kefituqere

**Comment by rhodey** [comment]
this issue is crazy old and our MMS code has changed many times over since, unfortunately all information in this issue is stale & cannot benefit us in improving MMS further. if anyone in this thread is still having issues with MMS please find a recent issue that matches your behavior and preferably network provider and add a debug log there.

Also RW is the enemy apparently
