### ISSUE TITLE
Wrongly displays "Error sending message" in groupchat.

### ISSUE THREAD

**Issue by lamade10** [WhisperSystems/TextSecure#2169]
When I send a message in this groupchat it SOMETIMES displays "Error sending message". If I then check the details of the message it shows that it tried sending by MMS. However the other people in the groupchat do receive the message and do so as a push message.

In the TextSecure settings I have SMS completely disabled (and so by extension also MMS).

My TextSecure version is 2.3.2. I have an Cyanogenmod rom installed.

This is the link to the part of my logcat where I tried sending a message in the groupchat that I got by adb (I deleted the phone numbers):

https://gist.github.com/lamade10/29b322679d2f1260ab71

**Comment by jayaddison** [comment]
I've seen this earlier today while running 2.3.3 - I was seeing 'Error sending message' alongside group messages.  After a bit of digging, it turns out that I had a slightly incorrect phone number for a recipient - it was missing a leading '+'; the contact was still identified correctly and messages could be received from that recipient but not sent.

**Comment by jayaddison** [comment]
(also note that the group definitely received duplicate messages when I attempted to resend the ones that were marked as failed)

**Comment by rhodey** [comment]
this multiple send issue described by @jayaddison is documented in #2639. anyone still experiencing the issue where sometimes group messages are sent as MMS when they should be sent as TextSecure messages over data/push?
