### ISSUE TITLE
hidden conversation when all messages deleted before writing new ones

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2262]
- enter existing conversation
- delete all messages
- ~~right~~(at least it sounds similar) write a new one 
- exit conversation
--> not in conversation list

**Comment by rhodey** [comment]
This issue occurs because...

When deleting all the messages in a thread the thread DB automatically deletes the thread, but ConversationActivity does not understand that the thread has been deleted so any new messages sent are inserted using the deleted thread ID. The next time a new thread is created the messages sent previously after the all-message-delete condition will magically appear in this new thread because thread IDs are reused in our DB.

**Comment by McLoo** [comment]
@rhodey thanks 🙇
