### ISSUE TITLE
Invite to TextSecure opens in browser and not in play store

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/TextSecure#2357]
Is this a bug on my side or due to the forwarding? On my nexus 4 the invite link opens the web version of the store and doesn't prompt an "open with play store" menu. Are you using https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms as forward target?

**Comment by rhodey** [comment]
The current invite link is `sgnl.link/zhrzvk6`, this 301's to `https://whispersystems.org/signal/install`, which then seems to do some JavaScript magic to detect platform (Android vs iOS) and forward onto Google Play or the App Store.

If we assume that the install link will be clicked from inside an android app we can use the URI `market://details?id=org.thoughtcrime.securesme` to show our app in the google play store Android app but this URI does not work in the browser. I think the problem is not knowing if the install link is going to Android or iOS or whatever else, this doesn't seem possible at this time.
