### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#2450]
https://gist.github.com/bf37af9dde8f0cb4bea1

**Comment by moxie0** [comment]
Did you edit this debug log?

**Comment by merkste** [comment]
No, I just posted it from my phone. Sorry if that got too verbose.

Am .02.2015, 18:04 Uhr, schrieb Moxie Marlinspike  
<notifications@github.com>:

**Comment by merkste** [comment]
Please let me know if I can help, e.g., with additional information.

**Comment by mcginty** [comment]
Are all images not being displayed, or just one?

**Comment by mcginty** [comment]
Also, do you know if this started on an incoming image, outgoing image, or when you were trying to attach?

**Comment by merkste** [comment]
Log after restart:
https://gist.github.com/9e33ffba03ad3357d307

**Comment by merkste** [comment]
Log after restarting my phone and scrolling some conversation. Strange enough, images are being displayed again. This was not the case after the restart before.
https://gist.github.com/354024fd76a13b26b40b

**Comment by merkste** [comment]
@mcginty The first time I noticed the issue was after sending an image. But it could be that I simply missed it before since there were no other images in the viewport of the recent conversations.
At first no images were shown but one. After restarting the phone another one was displayed but not the others. However, after 2 hours or so, no images were being displayed at all. After a second or third restart, alle images are being displayed again.

**Comment by mcginty** [comment]
I wasn't able to reproduce this, and my first guess of there being a missing file seems inaccurate if restarting helped. Another guess might be too many open files or some other form of resource exhaustion due to the leaked activities we had, in which case v2.5.2 may very well help solve these problems.

@merkste when we release v2.5.2, can you update the issue and let me know if you still have these errors? I'll try to look further into this after we get that release out, but it's not obvious to me right now what's causing it.

**Comment by merkste** [comment]
Today the pictures disappeared again which indeed seems a hint to a resource hog.
I'll look out for the problem once 1.5.2 is out - which happens to be right now, right? =)

**Comment by mcginty** [comment]
Going to close, please re-open if these issues are still around.

**Comment by merkste** [comment]
Ack. I haven't seen this again since the update to 1.5.2. Thanks!
