### ISSUE TITLE
New TLDs are not clickable links in a message

### ISSUE THREAD

**Issue by git12a** [WhisperSystems/TextSecure#2463]
TLDs like .post or .today are not clickable links. I don't know list of new ones like this that are not supported by Textsecure, but I'm sure someone here can get such a list to add it to textsecure. Due to this, one have to copy and paste the whole message to browser and then edit and load the page.

**Comment by kmindi** [comment]
Which version of Android are you using? Because this depends on Android not TextSecure AFAIK.
TextSecure uses `<TextView android:id="@+id/conversation_item_body"
        android:autoLink="all"[...]`

see http://developer.android.com/reference/android/util/Patterns.html#TOP_LEVEL_DOMAIN_STR
It states it is outdated but I did not find the new Pattern or way to go just yet ;)

**Comment by git12a** [comment]
Thanks for this information, @kmindi. Closing.
