### ISSUE TITLE
Relative timestamps not useful

### ISSUE THREAD

**Issue by ryanfox** [WhisperSystems/TextSecure#2465]
I'm not sure if this is a good place for this, but I can't find anywhere else to leave feedback on the app.  After the update a couple days ago, timestamps on recent messages became relative (e.g. "8 minutes ago").  This conveys less information, and the alternative (e.g. "12:34PM Feb. 12") doesn't take up materially more room on the screen.  What does "1 hour ago" mean?  I haven't tested it, but reasonable people could come to conclusions anywhere between 31 minutes and an hour and 59 minutes ago.

I'm using a Nexus 4, Android 5.0.1.

**Comment by tjoels** [comment]
I agree. 
Why was it collectively decided that instant messaging apps should use relative timestamps? Perhaps to ease differences between time zones?
I find it frustrating, because I then have to calculate time intervals differently depending on the type of timestamp.

It should be up to the user to choose the type of time stamps in settings.

Where do I go with this kind of feature request?

**Comment by greyson-signal** [comment]
> Where do I go with this kind of feature request?

You can discuss feature requests on our forum:
https://community.signalusers.org/
