### ISSUE TITLE
Crash Browser -- MMS Exception

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#2508]
`````
java.lang.RuntimeException: Value length > LENGTH_QUOTE!
at ws.com.google.android.mms.pdu.PduParser.parseValueLength(PduParser.java:917)
at ws.com.google.android.mms.pdu.PduParser.parseHeaders(PduParser.java:586)
at ws.com.google.android.mms.pdu.PduParser.parse(PduParser.java:110)
at org.thoughtcrime.securesms.jobs.MmsReceiveJob.onRun(MmsReceiveJob.java:43)
at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
`````

**Comment by dckhole** [comment]
I got this exact error after an MMS I received a few days ago, and after crashing it will not start up at all. I assume the offending message is in a "havent processed yet" queue and it keeps trying.
Any way to force it to erase just the offending MMS without dumping the entire app storage? My phone is not rooted, but could do that if it would be easy to fix by just e.g. deleting a file in the app's data dir. I can also provide more info as well since mine is easily reproducable.

**Comment by moxie0** [comment]
@dckhole Put your device into airplane mode, start textsecure, delete the message, then take your device out of airplane mode.

**Comment by aaronkurtz** [comment]
I'm getting the crash even in airplane mode.
Running 2.6.4.

**Comment by moxie0** [comment]
You'll have to post a debug log for us to know what's going on.  If it's crashing immediately, then the only way to do that is with logcat.

**Comment by aaronkurtz** [comment]
Upgraded to 2.8.0 and no longer experiencing the crash.

**Comment by dckhole** [comment]
The airplane mode approach didn't help me either- the application was attemping to parse this message on startup every time regardless of connection (same PduParser traceback you posted every time).
Fortunately, it was resolved for me as of 2.8.0 as well.
Thanks, @moxie0 !

**Comment by arashpayan** [comment]
My wife just started experiencing this tonight on her phone while using v2.9.2 (upgrading to 2.9.3 didn't help). I sent the crash report via the Google crash reporter. There was no way to get back into the app because it would crash immediately upon load. I had to delete the app's data in the Android settings to make it operational again.

**Comment by moxie0** [comment]
Hey Arash, how did you determine that it's this error?

On 03/31/2015 12:25 AM, Arash Payan wrote:
> My wife just started experiencing this tonight on her phone while using
> v2.9.2 (upgrading to 2.9.3 didn't help). I sent the crash report via the
> Google crash reporter. There was no way to get back into the app because
> it would crash immediately upon load. I had to delete the app's data in
> the Android settings to make it operational again.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/2508#issuecomment-87973731>.
> 

-- 
http://www.thoughtcrime.org

**Comment by arashpayan** [comment]
Hey Moxie,
I just looked in the logcat and saw the same stack trace that you posted at the opening of this bug whenever the app crashed.
`
FATAL EXCEPTION: JobConsumer-3
Process: org.thoughtcrime.securesms, PID: 3648
java.lang.RuntimeException: Value length > LENGTH_QUOTE!
 	 at ws.com.google.android.mms.pdu.PduParser.parseValueLength(PduParser.java:917)
 	at ws.com.google.android.mms.pdu.PduParser.parseHeaders(PduParser.java:437)
 	at ws.com.google.android.mms.pdu.PduParser.parse(PduParser.java:110)
 	at org.thoughtcrime.securesms.jobs.MmsReceiveJob.onRun(MmsReceiveJob.java:44)
 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
`

Then I searched the GitHub issues for 'pduparser' and here I am. :-)
