### ISSUE TITLE
Poll Feature

### ISSUE THREAD

**Issue by Pazuu** [WhisperSystems/TextSecure#2551]
First of all: Your work is absolutly awesome and my friends and i are very very thankful to be able to collaborate so easy, secure and undisturbed over the Internet!

When we work on projects for university we use a Textsecure group. And because we want to decide democratically on steps our group takes, dates of meetings or find out whos comming to an event we use doodle.com a lot.

It cant be done soon, but we would love to see a poll feature some day (maybe like Threema has implemented it). Perhaps in Signal for Android version 4.0 :o)

Because communication is the basis of everthing and your apps are all about communication, i think this feature would be fantastic!

Thank you so much! And keep on having fun with this great project!

**Comment by tehabe** [comment]
See #2530

**Comment by zmanian** [comment]
@tehabe Seems like @Pazuu  is requesting a rich GUI for messages related to picking between a list of options and not http polling to check for new messages. Apparently Threema has such a feature.

**Comment by tehabe** [comment]
Poll vs. polling. Okay, I got it now. Sorry, was confused an hour or two. Yeah, I know that Threema has such a feature but honestly, I think sites like Doodle are much better for such an issue.

**Comment by Diapolo** [comment]
Please don't bloat TextSecure...

**Comment by Pazuu** [comment]
I absolutly see the Point of "do one thing, and do it well", and i dont want to annoy with distracting feature requests. But is there a tool like doodle, which is transperent, respects your privacy and is easy for everyone to use?

**Comment by mcginty** [comment]
When we think about new features for groups, they will likely be more media-focused. Like you said, I think the need for a separate tool like Doodle that's privacy-preserving is a separate but valid issue that isn't in TextSecure's space. Thanks!

**Comment by StefanFabian** [comment]
@mcginty I think using separate tools like doodle for a quick poll is kind of overkill and it's also a hassle to switch apps all the time.
In group chats, a simple polling function would be an awesome outstanding feature.
It could also be in a human-readable format to preserve backward compatibility, e.g.:
```
:poll: Where do we want to go for lunch?
:option: italian
:option: vietnamese
```
Answers would simply be `italian` or `vietnamese` case-insensitive.
This wouldn't require changing any of the backend or transport code but only affect the presentation.

Since being the same as other messengers such as WhatsApp with security/privacy is not enough for most people to switch, maybe there should also be some compelling features to sell the app to people who don't seem to care much about giving all of their data to untrustworthy companies.
