### ISSUE TITLE
Had to re-register after upgrade to 2.6

### ISSUE THREAD

**Issue by alex42ka** [WhisperSystems/TextSecure#2609]
As described above. I wasn't able to receive and to send messages to my contacts after the upgrade to version 2.6. After I re-registered my number everything is working again as expected. My phone is the Oneplus One.
For my wife everything went fine. She is using a Nexus 4.

**Comment by johanw666** [comment]
I had the same issue. Sending secure and unsecure sms worked fine, but pushmessages would just disappear into the void.And now I can not send secure sms anymore, just unsecure sms and push.

**Comment by meteficha** [comment]
I and my brother had the same problem. Re-registering fixed the issue. We have a Moto X (2nd gen) and a Nexus 4 in stock ROMs. 

My mom's S3 running CyanogenMod didn't have any issues.

**Comment by clsec** [comment]
I only have one contact who uses TS and (this has been going on since before 2.6) I've been having lots of secure push disappearing to them. The only way (before 2.6) to re-establish a secure channel with them is to send them an unsecured sms and when they reply it is once again secured. But since I installed 2.6 (they have 2.6 as well) the *only* way we can communicate now is through unsecured sms. Another odd thing is that they are  now receiving my unsecured sms in Google Hangouts?!

Also, is it possible to re-register ones number without backing up and re-installing the app? Seems like a lot of work just to re-establish a secure channel..

We both have Galaxy Note II's, stock ROMs, Android v4.4.2. I'm on AT&T and I believe they are on T-Mobile.

here's my recent debug log:
https://gist.github.com/1004e8679778c250c9d3

**Comment by moxie0** [comment]
Ugh, sorry about this. Fix on the way.

**Comment by agrajaghh** [comment]
@clsec to re-register just uncheck "push messages" and check it again

**Comment by moxie0** [comment]
@clsec Hold that thought.

**Comment by moxie0** [comment]
Here's the state of the world:

1) I just pushed a change to the server side that will stop this from happening for all new messages.  So @clsec, you shouldn't have to do anything for TS to start functioning again.

2) The good news is that the messages aren't lost.  They're all queued up on the server, but people won't receive them until they upgrade to 2.6.1 (pending).

3) However, if you reregister, you *will* lose your messages queued on the server.

So my advice is to sit tight for now, and hopefully the update will come through Play soon.

**Comment by clsec** [comment]
Thank you for the clear explaination and your quickness in updating @moxie0 I will patiently await 2.6.1.
