### ISSUE TITLE
Empty dialer problem

### ISSUE THREAD

**Issue by AlexAlexandru** [WhisperSystems/TextSecure#2696]
So as you can see here there is a send message button
![sc20150315-145256](https://cloud.githubusercontent.com/assets/5292321/6656087/698738c4-cb24-11e4-8595-3f202112df45.png)
If I type something in the dialer is working as expected if its empty and press it I get here
![sc20150315-145308](https://cloud.githubusercontent.com/assets/5292321/6656089/7ed7461a-cb24-11e4-9b3b-02bdb0bd63f0.png)
and I cannot add contacts and if I type something the app crashes.So when the dialer is empty this is where the app should open
![sc20150315-145318](https://cloud.githubusercontent.com/assets/5292321/6656129/5b716a8c-cb26-11e4-96a9-a1d07107a28a.png)

android version 2.3.6 textsecure latest play store 2.6.4

**Comment by agrajaghh** [comment]
you could please post a debug log after TS crashed

**Comment by AlexAlexandru** [comment]
I don't think this is usefull https://gist.github.com/anonymous/34c58331c03a1353f6cd I just see force close and report

**Comment by AlexAlexandru** [comment]
![image](https://cloud.githubusercontent.com/assets/5292321/6656814/016cbf46-cb3f-11e4-958c-428a4ea08f09.png)
maybe this is can help you

**Comment by rhodey** [comment]
I created this simple app for testing of this bug: https://github.com/rhodey/SendIntentTest

Through testing I discovered that this bug happens when TextSecure receives an `Intent.ACTION_SENDTO` intent where the `Uri` returned from `Intent.getData()` does not contain a recipient, ex: `smsto:`

The result of `RoutingActivity.getConversationParametersForSendAction()` is a `ConversationParameters` where `threadId = -1`, `recipients != null`, and `recipients.getRecipientsList().size() == 0`

`RoutingActivity.handleDisplayConversationOrList()` ends up with the result from the aforementioned method and checks that `recipients != null` **but does not check if it is empty**.

Possible fixes:
1. add a check for `!recipients.isEmpty()` [here](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/RoutingActivity.java#L123)
2. refactor a bit more and route to `NewConversationActivity` as suggested by @AlexAlexandru

**Comment by rhodey** [comment]
this was resolved with the banishment of RoutingActivity, works now, tested with:

`$ adb shell am start -a "android.intent.action.SENDTO" -d "sms:"`
