### ISSUE TITLE
Offer SMS encryption under advance options.

### ISSUE THREAD

**Issue by BoBeR182** [WhisperSystems/TextSecure#2738]
Seems my last issue was closed without a response. 

I have a phone that does not offer Google Play Services and thus in the recent update 2.7.1, All my contacts lost the ability to reach me privately. With no data connection as part of my providers plan and only Wifi access in certain areas I relied on Textsecure as a 24/7 secure channel to contact me on.

I would like to see SMS added as a advance mode enabled option or could someone point me to another app or fork that allows me to send messages using the same crypto scheme.

**Comment by TheStash** [comment]
The response is that Open Whisper Systems have taken a decision to pull back this feature because of the reasons mentioned here (https://whispersystems.org/blog/goodbye-encrypted-sms/), and to focus on more important features.

**Comment by BoBeR182** [comment]
Is there any fork or other SMS encryption app to migrate to? Or am I just left high and dry with a different UI basically?

**Comment by TheStash** [comment]
There are forks made by securecom (https://play.google.com/store/apps/developer?id=Securecom+Mobile) but i have no idea if they are trustworthy, on the other hand Moxie and the team have taken a big hate (https://twitter.com/moxie/status/578939660430229504) so no need to pressure them more than this since they their work is voluntary in first place and open source so people passionate about the Encrypted SMS could fork it and build the app themselves.

**Comment by BoBeR182** [comment]
I have loved the work @moxie0 has been making the whole time and while I agree with his views that encryption should be transparent and simple.

I just find there is more friction with letting a random app register your phone number to some database, compared to allowing a round of key exchange SMSs.
I hope someone can add a advance user setting that allows the default to be the push data system, while allowing others to use SMS when they do not have access to the data network or cannot have access to Google play services.
