### ISSUE TITLE
Notification sound doesn't work upon installation

### ISSUE THREAD

**Issue by TurkeyMan** [WhisperSystems/TextSecure#2793]
I noticed after installation that when I receive messages, it didn't make a sound, it only flashed the notification light.
I go to Settings -> Notifications, and I can see "Sound = Argon" is displayed. I press on 'Sound', which takes me to the sound selection list, but here there is none selected. I now select Argon from the list, back in settings it says "Sound = Argon" as before, but from now the app is making notification sounds.

My colleague also had the same problem.

**Comment by ArchangelRenzoku** [comment]
I've had the same problem on my Note 3 (SM-N900T), first on KK 4.4.2 then Loli. The fix mentioned above was so easy I never bothered to report it but now that I've stumbled across this, might as well throw my 2 cents in.

**Comment by rhodey** [comment]
steps to reproduce:

1. have a copy of TextSecure installed where you have never opened the notification preference setting page.
2. make sure android notification sounds are enabled by pressing the volume + button a few times, if you're running Lollipop verify that "All" notifications are selected and not "None" or "Priority"
3. receive a message, notice no sound is played.
4. open the notifications settings page (Settings > Notifications)
5. receive another message, notice sound is played.

This bug occurs because the `android:defaultValue` XML attribute is only applied to an applications `SharedPreferences` via `addPreferencesFromResource()` or `PreferenceManager.setDefaultValues()`, so until the notification settings page is opened by the user the notification sound is actually `null`.

Potential fixes:

1. add [PreferenceManager.setDefaultValues()]([http://developer.android.com/reference/android/preference/PreferenceManager.html#setDefaultValues%28android.content.Context,%20int,%20boolean%29) to `ApplicationContext`
2. modifying [this method](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/util/TextSecurePreferences.java#L380) to return `content://settings/system/notification_sound` instead of `null` as the default.

To address this bug specifically I think we're better off going with option two as it has a more predictable outcome, option one could potentially affect other notification preferences.
