### ISSUE TITLE
Fall back to SMS if no data connection

### ISSUE THREAD

**Issue by fajabird** [WhisperSystems/TextSecure#2847]
I'm not absolutely sure, but I think in some former version of TS (maybe before dropping encrypted SMS) TS would aks if it should fall back to SMS if no data connection was detected. I have an ongoing chat with a friend where this happended when I send him a message and had not data connection at that moment. 

Today I tried the same (send a message to a TS contact while no data connection available)  with this results:
1. TS does not ask what to do
2. TS wants to send a encrypted message which will never succeed as long as device is offline
3. TS seems to have no timeout, so even after waiting for verly long no fallback to SMS
4. Sending manually a SMS is bad for 2 reasons: First - normaly I dont want to use SMS, so I intuitivly I want to just send a message thinking it will go out over data channel. Second - I had to use this issue-tracker to find out how to accomplish sending a SMS within an ongoing encrypted chat.... its kind of hidden.)

Suggestion: just ask the user via a pop-up what to do in situations where no data connection is available:
1. Send over SMS right away (only unencrypted)
2. Wait and send encrypted as soon as data connection becomes available
(additionally: remember decision for this chat/for all chats)

**Comment by fajabird** [comment]
Additional note: I cannot find the "SMS fallback" options in the preferences anymore with the latest Version of TS. Maybe I have disabled it in some former version of TS and now its still disabled? Or is this feature just has been removed?

**Comment by manhole11** [comment]
I think (but this is just my opinion) that the reason why SMS fallback has been removed is that SMS is not encrypted anymore. Think about this: textsecure aims to keep your conversations safe; if it sent uncencrypted SMSs all the time, it wouldn't be that secure.. right? You can think of it as whatsapp. If you send a message in whatsapp and you're offline, it won't ask you to send an SMS, simply because that's not what it does. You should see textsecure as an encrypted chat app which additionally handles your SMSs.

**Comment by manhole11** [comment]
Personally, I wouldn't want a popup. I am fine with ts retrying as long as it can. If there was a popup and I missed it, the message would never get sent.

**Comment by fajabird** [comment]
What about a immediate popup after pressing the send button? The network status is known in advance.

**Comment by manhole11** [comment]
That would be really annoying, as most of the time the lack of signal is just temporary. You don't want a popup just because you've been one second without signal..

**Comment by fajabird** [comment]
I understand your point - really. Still TextSecure wants to be a single solution for both chat and SMS and this is really still a unique feature (although already limited to unencrypted SMS only - which lead to some discussions). For most of my contacts I was only able to get people to TS by advertising them this as a drop in replacement for their SMS-application with some additional features like encryption and group chats - just because everybody already had 2 or 3 other chats apps. So please don't net me down on this :-)

TS tends to take meny decisions away from the user. If you prefer to use data only  - fine. If I prefer to use SMS-fallback all the way long - it should be fine, too. Until 2.6 it was the users choice - no discussions, just personal decisions. If you change default behaviour to prefer data - thats fine too, and there are reasons to do that (e.g. for people not seeking for a SMS replacement but just for a chat app). But as a SMS replacement you really should give the users more options to chose from. 

So what about this: if TS is not configured to be the defaulot SMS-application - disable SMS-fallback. If TS is the default SMS-app, let the user enable SMS-fallback in the settings  - no popup at this point. Now with enabled SMS-fallback: if a user sends a message while offline set a  timeout. If the message is not send in time show a notification in android notification bar. On touching this notificaton display some information and a option to fallback to SMS or just to wait longer. If the message gets delivered over data before user gets back to his mobile delete the notification.

**Comment by manhole11** [comment]
I feel like maybe it would be better to discuss this in the mailing list. If it were for me, textsecure would ditch SMS support today and that would be the end of it. MMSs are causing SO MANY problems, 90% of the developers' energies go into bu fixing them. And most people I know don't even use it to replace their default SMS app... actually, pretty much everyone I know doesn't like textsecure enough to replace whatever app they're using... and after all the "bad encrypted message", group chat not working etc, most of them have completely stopped using it.
I feel like it would be better to focus on ONE thing (=chat), and do that one thing well enough to attract users, or at least not repel the new ones.

**Comment by wp9015362** [comment]
@manhole11 :

I feel exactly the same and do fully agree. IMHO TextSecure should concentrate on chats via data and developers should pour all their energy and manpower into that instead of also having to struggle with SMS/MMS.

I really don't understand why the developers still support SMS/MMS at all even though they themselves said "SMS and MMS are a security disaster." (https://whispersystems.org/blog/goodbye-encrypted-sms/).

Unfortunately though a few hours ago @moxie0 said on the mailing list, that SMS support will not be removed, see:

https://lists.riseup.net/www/arc/whispersystems/2015-04/msg00008.html

I really do not understand the logic behind this. When you say "SMS and MMS are a security disaster." then why do you still support it?

Instead of continuing supporting SMS and MMS, you could better concentrate on things like getting rid of GCM for example IMHO.

And falling back to SMS or MMS might potentially be dangerous due to costs being involved with SMS/MMS delivery.

TextSecure really should be about communication via data IMHO. SMS / MMS should not be supported.

Oh, and why do I say this here and not on the mailing list?

Because the mailing list archive exposes the email addresses of each poster, which I don't like for privacy reasons.

Apart from that, posting on GitHub is more comfortable than on antiquated things like mailing lists IMHO. And I simply don't want to subscribe to a mailing list when I already have a GitHub account.

**Comment by rhodey** [comment]
I don't feel that this issue adds anything beyond what we already have documented in #678, #877, and #2384. maybe close as dupe?
