### ISSUE TITLE
Lollipop MMS broadcast never received when sending/receiving MMS

### ISSUE THREAD

**Issue by wb-higgins** [WhisperSystems/TextSecure#2872]
I have been using TextSecure for a short time and have not had any trouble with it until the most recent update.  After this update I receive an error about the MMS downloading any pictures I am sent.  Here's the link to my debug log:  https://gist.github.com/c601005eee6b12277f79.

Thanks,

**Comment by BienquistaBromista** [comment]
I am also having this issue. I cannot send or receive MMS messages. (But I can send images to other TextSecure users who have internet messaging enabled).

Here is my debug log: https://gist.github.com/anonymous/800c5a62a61d65e24b10 (the area starting at line 73 seems particularly relevant). 

My phone model: LG G3, running TextSecure version 2.9.2 on Android 5.0.1 (Lollipop). I'm also willing to run any experiments that you might need, if you're unable to reproduce the bug yourself.

**Comment by mcginty** [comment]
When you send MMS and it hangs then fails, can you confirm that it's actually not received by the person you're sending to?

**Comment by mcginty** [comment]
I'm wondering if Android's send logic is executed at all and we just don't receive the broadcast, or if it's more than just broadcast handling.

**Comment by BienquistaBromista** [comment]
I tried sending a few test messages to my Google Voice number and never received them. So it looks like it actually is failing, and not just missing the broadcast.

**Comment by mcginty** [comment]
Thanks for the quick response @BienquistaBromista. I wasn't able to reproduce this, but will look into it.

**Comment by BienquistaBromista** [comment]
Also, I don't think this issue is limited to Lollipop. My dad has a Galaxy S3, which I think is on KitKat, and he's also been able to send MMS messages since the latest update. (Also, both he and I are on Ting, which buys coverage from Sprint, if that's relevant.)

**Comment by mcginty** [comment]
That's likely a separate issue if it's on KitKat. If you could get a debug log from your dad, we can start investigating that as well.

**Comment by moxie0** [comment]
@wb-higgins and @BienquistaBromista, does MMS work for you with the stock MMS app (not hangouts)? We recently switched to using the Android system APIs for sending/receiving MMS, which means that the APN information is now drawn from what's configured in your system settings rather than from the APN database we were using.  Can you check to make sure that information is correct for your carrier?

**Comment by BienquistaBromista** [comment]
Yeah, it does work with other messaging apps for me. And I did check to make sure that the MMSC URL in my phone was correct.

**Comment by phipolis** [comment]
I have a friend also encountering this issue. [Here is their log](https://gist.github.com/anonymous/50b38007edc1dc66bcf5) after an incoming MMS group message triggers a "MMS download failed!" Nothing stands out to me, but who knows.

**Comment by arlenarlenarlen** [comment]
I'm having a similar (identical?) issue receiving MMS from iOS users, presumably using the stock messaging app. This is a problem for both 1:1 picture messaging as well as group messaging.

Here's my debug log: https://gist.github.com/87bb9a7daf2c263ffd04

**Comment by mcginty** [comment]
Thanks @arlenarlenarlen. cc @wb-higgins and @BienquistaBromista, some clarifying questions since I'm unable to reproduce:

1. Is this a periodic problem or persistent? Can you ever receive or send MMS?
1. When this is happening, do you have your data connection enabled, and does it have decent signal and bandwidth?

I'm wondering if this is an issue with us needing to allow more than 30 seconds for a message to send...

**Comment by arlenarlenarlen** [comment]
@mcginty it fails most of the time. Last successful MMS was March 13th which was an extended group conversation with long delays and some failures. I don't remember if Textsecure has been updated since then. I'm usually on WiFi or LTE. WiFi is reasonably fast ~25Mbps, LTE isn't the greatest signal strength, getting about 6Mbps from the location where I posted the debug log.

**Comment by darkSkies** [comment]
Using TextSecure on an S5, AT&T is the carrier. CyanogenMod ROM. 

Haven't been able to receive MMS from any non TextSecure or non Signal users for about 2 weeks. Unfortunately, this is basically most people in the world. 

Debug log:

https://gist.github.com/e31c45fbca83c5fb8c7c

**Comment by mcginty** [comment]
Thanks for the log, @darkSkies. The phone I used primarily for testing MMS was on AT&T and I didn't have problems with it, so it's unfortunately for reproducability it's not a problem with the entire carrier...

**Comment by darkSkies** [comment]
@mcginty, any suggestions on how I can remedy this problem?

**Comment by alexandreboivin** [comment]
This issue is still occurring for me after the latest update. There are errors on every attempt to send ("Failed to send" error) or retrieve ("MMS download failed" error) MMS to non TextSecure users. Sending or receiving MMS works fine with the stock messaging app, and this happens even when I have excellent signal strength.

Here's the log from the latest failed MMS https://gist.github.com/anonymous/1de898ef3e85dbc8c4e7

I'll have to switch back to the stock app as my default SMS application until this issue is resolved, but please let me know if there's any more info I could provide that would help you out.

**Comment by darkSkies** [comment]
My wife and I just tested this again. TextSecure is my default messenging app...

She took a photo with her iPhone and sent it to me from the stock iOS messaging app. I received a message that said "downloading MMS" & after a few seconds that message changes to "MMS download failed".

Please let me know if I can help you fox this. I have a couple of iDevices and my Android device to work with; I'm having problems getting this to work with either system.

Debug log:

https://gist.github.com/4e6fe25ff906955d967a

**Comment by willbuckner** [comment]
It really sucks because this has been broken for weeks and I've been patient but every update doesn't fix it. It worked fine for more than a year but it's been broken for over a month. Just tries connecting to MMS server for 30+ seconds and fails. Going to have to use an insecure app again because I've missed so many MMSs from friends and colleagues. I have to tell them all to "try Kik or Facebook"  :( I have an HTC One m8 on VZW running 5.0.1. Can't figure out how to modify or verify my APN at all either, but it always worked before until a TextSecure update. Have you guys considered just reverting to the old method, or making it an option at least? I want the whole world to use secure messaging, but my friends and I are going to have to go back to stock messaging... Sigh.

**Comment by JurisHacker** [comment]
I have the same issue on a oneplus (Cyanogen OS 12.0) running Textsecure 2.12.0.  Can't send or receive any MMS on the ATT network.

**Comment by mcginty** [comment]
Just pushed a change to 2.14.0 that means we no longer rely on the Lollipop API for sending MMS in lollipop. Should help this issue.
