### ISSUE TITLE
Update to 2.10.0 deletes Icon from Android favs

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#2878]
Not a really huge bug, but I'll report anyway: 
The most recent update deleted the TextSecure icon from my app bar. First time something like this happened. Re-adding succesful

Running on Cyanogenmod 11.

**Comment by wp9015362** [comment]
@mad-de 

Where did get TextSecure version 2.10.0 from?

The Google Play Store currently still seems to be at 2.9.3, see:

https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms

**Comment by agrajaghh** [comment]
@wp9015362 there is a beta channel: https://plus.google.com/communities/114424213916773497091

**Comment by mcginty** [comment]
Yeah, I think this happens since the launcher intent changed to point to ConversationListActivity instead of RoutingActivity. We could try including a skeleton RoutingActivity, but even then I think the issue is that the intent filter changed for `android.intent.category.LAUNCHER/android.intent.action.MAIN`

**Comment by moxie0** [comment]
Yep, don't think there's anything we can do about this.
