### ISSUE TITLE
[Beta 2.10.2] Blank Conversation when returning from Screensaver Activity indicator to new message

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#2920]
Hard to reproduce, but seems to happen most of the time, when I was on the Main Screen or in another Conversation and Screen Saver switched on. If I get a notification and use the Andoird Acticity indicator to read the new message, the TextSecure Conversation is empty at first (white) and can only be accessed upon clicking on the screen or going back to the main menu.

Running on Cm 11
https://gist.github.com/anonymous/1c6de393931e4bb41ee9

**Comment by moxie0** [comment]
@rhodey This sounds like that adapter change again maybe?

**Comment by rhodey** [comment]
@mad-de I'm not sure what you mean by "Andoird Acticity indicator", can you let me know what screensaver app you have installed?

tests run against b692d48b98eabd7f7c8c04880b977fb7b049e9a2 on Nexus 5 w/ stock Android:

## 1 - open convo from main screen
1. TS open, waiting in main screen
2. receive push message, conversation preview updates
3. tap conversation
4. messages displayed as expected

## 2 - display off, open convo from main screen
1. TS open, waiting in main screen
2. turn display off / sleep
3. receive push message, notification shows up on lock screen
4. unlock device
5. tap conversation
4. messages displayed as expected

## 3 - open convo from notification while in other convo
1. TS open, waiting in convo A
2. receive push message for convo B, notification shows up
3. tap notification
4. messages displayed as expected

## 4 - display off, open convo from notification while in other convo
1. TS open, waiting in convo A
2. turn display off / sleep
3. receive push message for convo B, notification shows on lock screen
4. double tap notification from lock screen
5. unlock device
6. messages displayed as expected

Do any of the above tests result in the bug you're describing? If not, could you please detail the specific steps, in order, that you go through when experiencing this bug? Thanks for the help :)

**Comment by mad-de** [comment]
Hey @rhodey thanks for your attention for this matter. I'm sorry for not having expressed me correctly, with the Activity Indicator I was referring to the notification indicator. So it's number 4, that caused this bug, but I'll see to test it out more thoroughly when I can get my hands on a second device.

**Comment by mad-de** [comment]
Okay. Have been able to reproduce behaviour. I switched. Happens, when I'm switching to Convo via notification bar, when I was in a different Convo before and had a different app open. Both with screen on or off. Happened 50% of the time. Might be due to my phone settings (cyanogenmod). But i havent Seen that behaviour in any other APP.
New log file: https://gist.github.com/anonymous/460b8887c0ad64558bd0

**Comment by rhodey** [comment]
thanks for the detailed update @mad-de :) let me try some more tests, documented below...

## Nexus One, stock Android 2.3.6, TS 2.10.2 from b692d48b98eabd7f7c8c04880b977fb7b049e9a2
### 1 - receive msg while in other convo and in background
1) open TS
2) click on conversation A
3) tap the "home" hardware button
4) open the Calendar app
5) receive push message from conversation B
6) tap notification
7) messages displayed as expected
*note, above test run through 8 times with same results*

### 2 - receive msg while process killed from other convo
1) open TS
2) click on conversation A
3) tap the "home" hardware button
4) open the Settings app
5) force stop TS
6) receive push message from conversation B
7) tap notification
8) messages displayed as expected
*note, above test run through 8 times with same results*

## Nexus 5, stock Android 5.1, TS 2.10.2 from b692d48b98eabd7f7c8c04880b977fb7b049e9a2
### 1 - receive msg while in other convo and in background
1) open TS
2) click on conversation A
3) tap the "home" hardware button
4) open the Calendar app
5) receive push message from conversation B
6) tap notification
7) messages displayed as expected
*note, above test run through 8 times with same results*

### 2 - receive msg while process killed from other convo
1) open TS
2) click on conversation A
3) open recent activities view
4) swipe TS to close it
5) open Calendar app
6) receive push message from conversation B
7) tap notification
8) messages displayed as expected
*note, above test run through 8 times with same results*

@moxie0 are you sure that b692d48b98eabd7f7c8c04880b977fb7b049e9a2 is what built play store beta 2.10.2? @mad-de can I get a sanity check that you're definitely running 2.10.2 :P also, what version of Cyanogen are you running?

anyone else with a Cyanogenmod device able to reproduce the behavior detailed by @mad-de?

**Comment by rhodey** [comment]
also, getting these tests run on another KitKat device, cyanogen or not, would be super helpful :)

**Comment by mad-de** [comment]
Hey @rhodey thank you for your time and efforts. For sanity check see attached logs stating: "App     : TextSecure 2.10.2"

Might take me a while to get the tests done appropriately, but I'l see to do them asap.

**Comment by rhodey** [comment]
got ahold of a kitkat device, non-cyanogen though :/

## Sony XPERIA, stock Android 4.4.4, TS 2.10.2 from b692d48b98eabd7f7c8c04880b977fb7b049e9a2
### 1 - receive msg while in other convo and in background
1) open TS
2) click on conversation A
3) tap the "home" hardware button
4) open the "White Noise Free" app
5) receive push message from conversation B
6) tap notification
7) messages displayed as expected
*note, above test run through 10 times with same results*

### 2 - receive msg while process killed from other convo
1) open TS
2) click on conversation A
3) open recent activities view
4) swipe TS to close it
5) open "White Noise Free" app
6) receive push message from conversation B
7) tap notification
8) messages displayed as expected
*note, above test run through 8 times with same results*

**Comment by McLoo** [comment]
4.4.4 Sony stock :
calendar: shows convo B
swipe kill: shows convo B
Force stop: no notification at all - for 5 minutes. Then opened TS from launcher and received msg after unlocking. 

CM 12 HTC 
same as above 

Though not gone through 8 times...

**Comment by rhodey** [comment]
@mad-de would you be willing to build or install a debug TextSecure apk in order to help determine what is going on here?

Ideally there would be a bunch of `Log.d()` logging statements added to [ConversationActivity](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/ConversationActivity.java), [ConversationFragment](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/ConversationFragment.java), and [ConversationAdapter](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/ConversationAdapter.java)

Adding a log statement to all of the methods with `@Override` annotations and additionally some of the initialization methods should give us a real clear idea of the state your app is in when this happens. Additionally, 2.10.2 should have just hit the google play store non-beta release channel yesterday, as a sanity check could you try updating to that first to make sure that you can reproduce this behavior still?

thanks for all the support in figuring this out :)

**Comment by mad-de** [comment]
@rhodey sure thing, send it over!
I was about to try 2.11 first, but I could do a fresh install of 2.10.2 from the non-beta channel, as I noticed this bug after updating to 2.10.2 from the beta channel. What would you recommend?

**Comment by rhodey** [comment]
@mad-de sorry for the delay in response, just finished creating the special debug apk. You can find the source for this apk in my [madde-test-apk branch](https://github.com/rhodey/TextSecure/tree/madde-test-apk).

I created this by branching off of the 2.11.1 release (commit 3e29bf4e542c27e306ff34347225cc1dfdd10f21), you can [review the diff](https://github.com/rhodey/TextSecure/commit/2b58b36049b18bd790d5e050e9992265a86ef6a0) to verify that the only edits here are new logging statements. If you feel more comfortable building this yourself you can do so by checking out  my branch and following [our build instructions](https://github.com/WhisperSystems/TextSecure/blob/master/BUILDING.md).

Please find the apk download [here](https://github.com/rhodey/TextSecure/releases/tag/2.11.1-mad-de). Take note that because this apk is signed with my debug signing keys you will not be able to install this on your phone without first uninstalling any previous TextSecure releases. I recommend doing a full backup with adb over the TextSecure built in export feature. Send an email to rhodey@anhonesteffort.org if you'd rather verify the file hash via email.

thanks again for all your support in helping resolve this :)

**Comment by mad-de** [comment]
Just a quick update - Problem still occurs occasionally in the latest beta version. As my USB cable broke, I'll have to wait for a new one to do a full dba bakup to install the logfile version, you kindly built. Sorry for keeping you in line for so long - quite busy with my courses right now. Thanks for your efforts and your great work.

**Comment by rhodey** [comment]
no worries @mad-de :). let me know when you've got the time and I'll make a new debug build targeting whatever beta is most recent at that moment.

**Comment by rhodey** [comment]
@mad-de are you still experiencing this behavior in 2.13.0? I've yet to see any other reports of this kind of thing.

**Comment by mad-de** [comment]
Yep still same behaviour occasionally. Nothing changed so far. I ll push for an ADB backup AS soon as I'm done moving into the new flat.

Cheers and thanks for your patience!

**Comment by mad-de** [comment]
Haven't been able to reproduce the behaviour since 2.16 update. Therefore I'm closing this issue. Sorry for the hussle for you guys.

**Comment by rhodey** [comment]
awesome :D thanks for checking back in
