### ISSUE TITLE
Bad encrypted message with two phones sharing the same number (Dual-SIM)

### ISSUE THREAD

**Issue by kellerkind** [WhisperSystems/TextSecure#2927]
I have text secure running on 2 android phones. One phone I use for work (MMB Gingerbread 2.3.7) the other is for private use (CM11). Both phones have a SIM card that uses the same number (in Germany called Dual-SIM). I migrated the text-secure setup from private phone via Titanium backup to the work phone. There was no new key-generation process on the work phone required. Btw. the work phones firmware is also missing the google-services so a reauthorisation is not possible at all. When I talk about messaging this means transport via Internet.

Steps to reproduce:
1. Start conversation on my private phone. 
2. Outgoing messages from my private and my work phone always receipt successful. 
3. Incoming encrypted messages on my private phone are fine
4. Incoming encrypted messages on my work phone are always corrupted (Bad encrypted message).

**Comment by agrajaghh** [comment]
You can't use the same Textsecure account on both phones, the internal state of the database will be broken on one device. In general TitaniumBackup isn't recommended since its often causing trouble. But multi-device support is on the roadmap. Using TS on a phone without google services doesn't make sense anyway for now sice you won't receive push notifications without the google services.

**Comment by moxie0** [comment]
Yeah, what you're describing will definitely break TS.
