### ISSUE TITLE
Implement "Quick Responses"

### ISSUE THREAD

**Issue by MatejKovacic** [WhisperSystems/TextSecure#299]
Android has an useful option for rejecting call with SMS. When you receive a call, you can reject it with pre-prepared or custom SMS.

However, this SMS is not sent through TextSecure but through default Android application for sending SMS's.

Can this be changed?

**Comment by fajabird** [comment]
Hi,
seems this issue still persists. What about implementing a small toast-message after someone tries to reject a call with a message that this funtionality is not supported yet because I already had some people asking me (the guy who recommended TS) what happened to their reject-messages. Or is someone already working this out?

**Comment by fajabird** [comment]
Ohh - I just took a look at the code and a "not supported yes" toast-message seems to be already implemented:

Toast.makeText(this,
getString(R.string.QuickResponseService_sorry_quick_response_is_not_yet_supported_by_textsecure),
Toast.LENGTH_LONG).show();

BUT it does not show up for me? Someone else getting that toast?

**Comment by McLoo** [comment]
@fajabird shows up for me. Rejecting call with text ends up in rejecting with 'not supported' toast following :)

**Comment by merkste** [comment]
I'd like to see the quick reply feature working, too. Any news for us on this one?

**Comment by asafh** [comment]
@merkste, unfortunately I don't see myself tackling this in the immediate future - since I don't want to uninstall TextSecure from my daily phone. When I get a secondary phone (not too long I hope, but I can't promise nothing) I'll look into this again.

**Comment by JavaJens** [comment]
@asafh You could:
a) Install two TextSecure versions in parallel and test with the browser extension (very buggy)
b) Specify what needs to be done to continue your development efforts and maybe point others in the right direction

**Comment by asafh** [comment]
@JavaJens what I've done and moxie's input on what needs to be done is described pretty well over PR #962. Basically, what needs to be done is trying to get the key from the key caching service directly, if it is available go ahead with sending the message, otherwise show a toast with the "TextSecure is currently locked. Quick Response messages are disabled." or similar.  

Since the code base has already changed quite a bit, I would the code in that PR's commit as a reference. It will be easier to simply do the similar work on a new branch from main.  

If you decide to tackle this, and have questions you want to consult me about - feel free to send me a message here or at ["hello",String.fromCharCode(31\*2+2)/\*regex scrapper\*/,"ous",".im"].join("")
