### ISSUE TITLE
Cannot get rid of message asking for a switch to TextSecure messages

### ISSUE THREAD

**Issue by jondo** [WhisperSystems/TextSecure#3011]
My child does not have a data plan on the phone yet, but still uses TextSecure (and I do not want to switch it back to the normal SMS app). How can I disable the nag message about activating TextSecure messages, which is covering 40 % of the screen?

**Comment by mcginty** [comment]
Hey @jondo, after encrypted SMS was removed in a recent release, we no longer allow dismissal of the registration message as it's such a vital part of the app and the only way you can communicate securely.

Generally speaking, TextSecure is designed to be used as a hybrid data/SMS app rather than just unencrypted SMS.

Thanks!

**Comment by jondo** [comment]
My child will get a data plan when it's old enough for that. Please make the message just pop up every month. Alternatively, please make TextSecure notice the missing internet connection (which will make registration fail anyway) and replace the message by a short "Hint: internet access would increase your privacy."

**Comment by bungabunga** [comment]
but why does he need to have TextSecure anyway if he can't use it's basic feature?

**Comment by jondo** [comment]
She was using it with encrypted SMS since last summer.

**Comment by moxie0** [comment]
https://whispersystems.org/blog/goodbye-encrypted-sms/
