### ISSUE TITLE
TextSecure should use keyboard emoji key if available

### ISSUE THREAD

**Issue by vinilox** [WhisperSystems/TextSecure#3026]
Since version 2.10.x, the emojis key (in the left of the input field) is always present even if the device has a emoji capable keyboard like the Google keyboard.
On my nexus 4 (android 5.1 gogole keyboard), after the 2.10.x update I have this left emoji key which is less convenient than the keyboard emoji key. Plus the keyboard emoji key save the most used emojis for all applications. The emoji drawer integrated in TextSecure only save the most used for TextSecure, I think it's not really convenient.

This issue seems to be related to https://github.com/WhisperSystems/TextSecure/commit/2f20bb89f3b64701d047fa3af2aa8b6e0ecfdc34

Dear developers, can you please use the emojis capable keyboard if it's available or add an option to use the TextSecure emoji drawer or not use ?

Thanks for reading this.

**Comment by agrajaghh** [comment]
please have a look at #2302

**Comment by vinilox** [comment]
I saw that thanks but like someone sauf before the TextSecure emoji drawer is a replica of the Google keyboard emoji drawer and this is a waste of space. Can't we use Google keyboard if available because TextSecure is using the samedi emoji set and this would save some space ?
There have been a comparison to Hangouts and Hangouts uses the google keyboard emoji drawer if available
-- 
Vinilox
Clé GPG : B6F475FD
XMPP : vinilox@vinilox.eu

**Comment by johanw666** [comment]
This was changed deliberately because not all keyboards have an emoji drawer. Several 3rd party keyboards don't and even the default keyboard of the Galaxy S5 doesn't provide that.

**Comment by wp9015362** [comment]
IMHO, TextSecure should not use native Emojis, since not all Android devices have the same native Emojis.

Samsung is using it's own Emoji set, LG is using it's own Emoji set, HTC is using it's own Emoji set, Google is using it's own Emoji set and so on...

And they all look different from each other, which can lead to an issue which is that Emojis can get lost in translation as described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

So, IMHO TextSecure should use it's own built-in Emoji set and it's own built-in Emoji drawer, so that all TextSecure users have the same Emojis.

This is also being discussed in the following issues:

https://github.com/WhisperSystems/TextSecure/issues/2892
https://github.com/WhisperSystems/TextSecure/issues/2894
https://github.com/WhisperSystems/TextSecure/issues/2936

Telegram for Android and WhatsApp for Android are doing it like that as well (they are using a built-in Emoji set and Emoji drawer, which replace the native Emojis).

Emojis ideally should be consistent across all devices and all platforms IMHO.

Regards

**Comment by mcginty** [comment]
thanks for opening the issue @vinilox, but yes we made this switch to maintain consistency across Android versions and third-party keyboards. As of yet, this seems to be the most reliable way to ensure android users have access to a full emoji set.

**Comment by vinilox** [comment]
@mcginty @wp9015362 @johanw666 Thanks for all the answers. It makes sense to do it your way :)

**Comment by peteyblueeyes** [comment]
@mcginty I frequently receive SMS messages with emoji that aren't in Signal's emoji set. Is there a way to see when they were last updated? To use some other set on my client? I appreciate the desire for consistency across platforms, but this also means that the maintainers of Signal have to keep up with changes and additions made elsewhere.

This may be atypical, but I use Signal for both SMS and secure messaging.
