### ISSUE TITLE
Textsecure crashes in Select contacts screen, can't send crash report

### ISSUE THREAD

**Issue by jerkey** [WhisperSystems/TextSecure#3052]
1) open textsecure 2.12 (push registered, Nexus 4 Android 5.0.1 build LRX22C)
2) touch the blue circle with the pencil in it
3) don't wait for TEXTSECURE USERS list to populate
4) start typing letters (1 to 3 is all it takes)
5) "Unfortunately, TextSecure has stopped."
6) click "REPORT"
7) can't proceed with report because soft keyboard is still up.
8) press Back arrow, bug report and textsecure disappear (no report filed)

debug log:  https://gist.github.com/anonymous/f2ea70697c14049ef969
![tscrash](https://cloud.githubusercontent.com/assets/1930655/7310035/8d1d0172-e9da-11e4-950d-abbe14d69a2c.gif)

**Comment by rhodey** [comment]
thanks @jerkey :D we got reports of this just a few days ago in issue #3004, it's surprising to me that this occurs every time for you though. @mcginty just added a fix for this issue a few hours ago in this commit b3707021b1af8dffa34fc23be91120c497756571

the fix is now in master and we're hoping a new release will be out today, if this issue persists after you update to that release please let us know and I'll reopen this issue.
