### ISSUE TITLE
TextSecure push messages reach after a delay, do not reach unless the TextSecure app is in focus.

### ISSUE THREAD

**Issue by TridonP** [WhisperSystems/TextSecure#3077]
I would like to help make TextSecure better. This is my first attempt at filing a debug log. 
As mentioned in the title, I find that TS push messages reach me after a considerable delay and only when the app is back in focus, as in, when TS is in the foreground. If I have to switch apps, messages to me aren't delivered but the moment I open TS and select the particular contact, the pending messages come streaming in.

I'm using TextSecure 2.12.0 on a Moto G running CM 12.1 with the Pico variation of GAPPS.
I can provide additional info as required.

Debug log from my phone : https://gist.github.com/6b3a93e8d7be140f96e6
Debug log from a friend's phone https://gist.github.com/050506894c5fd2ca379d

**Comment by moxie0** [comment]
Hey @TridonP, that means you're not receiving GCM messages.  I don't know what the "pico" variation of gapps is, but it sounds like that's probably the problem.

**Comment by TridonP** [comment]
Let me explain the Pico variation : This package is designed for users who want the absolute minimum GApps installation available.
In this package you will find the core Google system base, Google Play Store, Google Calendar Sync, and Google Play Services.

http://forum.xda-developers.com/android/software/reborn-gapps-5-t3074660

How do I troubleshoot this further ? Any others logs I could provide ?

**Comment by moxie0** [comment]
Whatever it is, you've got a bad gapps install that isn't receiving GCM messages.  Could also happen if you used something like Titanium Backup or other weird rooted shit on TS.

**Comment by TridonP** [comment]
Okay, I'll flash the regular GAPPS package. How do I determine whether I'm receiving GCM messages or not ? I'll keep testing and report back. Yes, my ROM does have root access. I'll keep testing and try reinstalling to see if it fixes the issue. I appreciate your time and help @moxie0 :)

**Comment by moxie0** [comment]
You'll see GCM messages arrive in the log. You'll have to re-register TS if you change your gapps package.

**Comment by TridonP** [comment]
Thanks, I'll get right onto it ! :)

**Comment by lucmil** [comment]
Hi, I'm seeing the same behaviour on phones with stock ROMs. Two messages  sent last Saturday, came in on Thursday (2015-05-21). I'm using the password protection feature available in TS and the message showed up after I punched in my password. It's also possible that I haven't opened TS once after starting up the phone. Is there any guaranteed upper bound on the time of delivery of push messages?

Here are the logs from both the sender (Sony) and recipient (LG) phones:
https://gist.github.com/anonymous/e51256bc14cd8be88d7a
https://gist.github.com/anonymous/0128681e715818813b1c

I'm not sure if the messages have been logged in there because I don't own the phone the message was sent from. If you could give me some pointers, I can try to reproduce this by sending messages from another phone I have.

**Comment by moxie0** [comment]
@lucmil If you're receiving delayed messages it means either:

1. You have background data turned off for either TS or a Google service.
2. You have a bad gapps install.
3. You've used Titanium Backup or something like it.
4. You have a network that blocks GCM.

**Comment by hgmichna** [comment]
Not every user can use GCM for one reason or another. Since these cases happen not too rarely, a solution is needed. Fortunately there is a reasonably good way out.

First let TextSecure detect the problem. This is not too difficult. If TextSecure keeps receiving messages just after it is opened and not much later, you can assume that GCM is not working. If TextSecure keeps receiving messages long after they have been sent, you can also assume that GCM is not working.

In this case let TextSecure revert to pulling. Pull automatically at a frequency that does not drastically increase battery consumption.

On top of that, detect ongoing discussions and increase the pull frequency until messages become infrequent again. I am sure somebody can come up with a clever formula for optimal pull frequencies. My best guess is to pull once a minute after an outgoing message for five minutes. Then pull once every two minutes for another 10 minutes. Gradually keep reducing the pull frequency and finally settle into pulling only once an hour if there has not been any traffic during the last 12 hours.

I have no idea about actual battery consumption for pulling, because the function does not exist yet. So please adapt the idea to actual findings.

I am not a great fan of settings, so please do not add yet another user setting.

**Comment by jedie** [comment]
Same as: #4266
