### ISSUE TITLE
ts stopped sending push messages

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#3108]
https://gist.github.com/e1a6897b2336f48db3b9
I don't seem to be able to send push messages to this contact anymore. Haven't tried other contacts as i don't have anything to say to anyone else :/

**Comment by volcano99** [comment]
I sent an empty sms hoping it would somehow wake up something but it didn't work

**Comment by volcano99** [comment]
W/OkHttpClientWrapper(31966): java.net.SocketTimeoutException: SSL handshake timed out
W/OkHttpClientWrapper(31966): 	at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
W/OkHttpClientWrapper(31966): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:371)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:241)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.Connection.connect(Connection.java:158)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.Call.getResponse(Call.java:262)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.OkHttpClient$1.callGetResponse(OkHttpClient.java:129)
W/OkHttpClientWrapper(31966): 	at com.squareup.okhttp.internal.ws.WebSocket.connect(WebSocket.java:160)
W/OkHttpClientWrapper(31966): 	at org.whispersystems.textsecure.internal.websocket.OkHttpClientWrapper$1.run(OkHttpClientWrapper.java:59)


I found this, and here's the thing (maybe it helps). When I sent the first message, I was at a train station where internet connection is really slow (probably because of the too many people). So maybe that's when the handshake timed out. After that, I did try to send some other messages, but maybe the fact that it couldn't do the handshake the first time prevented following attempts to succeed.
The only way to make it work again was to disable and reenable data

**Comment by clsec** [comment]
I seem to have the same issue. Whenever I send a push to my one TS contact it never goes through. The *only* way we can get a connection is if they initiate the conversation or if I re-register with the server. Strength of connection does not affect it one way or another (I use ATT 4G & they have T-Mobile 4G). I had initially thought it had something to do with the fact that they use Google Hangouts for everything except our secure push convo's, but after seeing this post it looks like it's the SSL handshake.

We're both using the latest version of TS & have Galaxy Note II's. We're also both using TS only for push. I use stock messenger for SMS and they use Hangouts for SMS.

debug log after fail: https://gist.github.com/21b0d78a44b0f48245aa

debug log after re-registering & message success: https://gist.github.com/762208d2935490a4944f

**Comment by clsec** [comment]
Another thing, they say they will not get my messages until they re-boot their phone. And when they do re-boot they say all my past failed messages will come flooding in. Unfortunately they are not on github, and we have a currently working convo, so I can't submit their debug logs right now. But the next time I have a bunch of failed msgs I will send them a regular sms & tell them to re-boot their phone. After all the failed msgs come through for them I will have them submit a debug log and then give me the URL so I can post it here.

**Comment by EvanK** [comment]
I've had a similar issue just today, where one particular person had sent me multiple (push) messages, none of which were received. I sent a test message back, which they did not receive.

**Comment by riyapenn** [comment]
@clsec @EvanK Check out http://support.whispersystems.org/customer/en/portal/articles/2121929-why-is-there-a-delay-in-receiving-messages- for both you and the contact you are experiencing this issue with.

**Comment by clsec** [comment]
Sorry, I should have reported here that this issue/bug is closed for me (& my friend). It was resolved in an update following my original posts in this thread. As for those suggestions, my friend and I had done all of those things at the time and they didn't work for us. Either way, it's resolved for us. Thanks!
