### ISSUE TITLE
[minor] hanging pixel line in emoji drawer, when scrolled to bottom

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3229]
Scroll end  position should be moved 1-2 px down, to Avoid hanging pixels, like the tire parts in the Screenshot 
They move along when sliding the taps - as tires do...

![_20150521_234456](https://cloud.githubusercontent.com/assets/5326916/7759686/e1959c2e-0013-11e5-9b83-636d37580ba6.JPG)

*I wan't the dark drawer back ( dark theme)*😭

**Comment by agrajaghh** [comment]
I guess this highly depends on the screen size and font size and its not possible to make it perfect on every device, its looking different on my Nexus 4 and HTC Desire

**Comment by wp9015362** [comment]
> @agrajaghh wrote:
> 
> I guess this highly depends on the screen size and font size

It would also depend on the keyboard size (the height of the keyboard).

And yes, it also depends on the system font size, see:

https://github.com/WhisperSystems/TextSecure/issues/2937

> @McLoo wrote:
> 
> I wan't the dark drawer back ( dark theme):sob:

I have specifically asked for the Emoji drawer background to be made brighter, see:

https://github.com/WhisperSystems/TextSecure/issues/2941

Some dark Emojis simply are incompatible with a dark background, since they can no longer be seen due to insufficient contrast.

Regards

**Comment by mcginty** [comment]
With time, I think having the emoji pane react to theme selection makes sense. Feel free to open an issue to track a dark theme for emoji panel.

As for this issue, the emoji panel has a dynamic height depending on the size of the system keyboard, so we can't make things align this nicely, realistically speaking.
