### ISSUE TITLE
Make the emoji panel back color theme dependent 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3240]
In other words:
Turn off f the light for the li'l fellas' home, when it's dark outside
 🌞🌚

**Comment by 2-4601** [comment]
Agreed. Now the dark theme with the emoji drawer open looks like someone wearing white tennis socks with a full black suit.

I understand the argument that dark colored emojis can get lost in a dark background but when you use the TS dark theme and you type a dark colored emoji it will still vanish at least once because the input box itself is black.

Here are examples of Lollipop's dark themed system keyboards and how their emoji drawers' backgrounds look like:

**Material Dark keyboard:**
![material dark](https://cloud.githubusercontent.com/assets/174176/7780777/17377a2c-00ec-11e5-9e12-e079cbd74dab.png)

----------

**Holo keyboard:**
![holo](https://cloud.githubusercontent.com/assets/174176/7780784/20a173f6-00ec-11e5-824e-b598dc49a5c3.png)

Even in the system keyboards some emojis will get lost in the background but that's the price of the dark side. You full well know what you get yourself into when you switch the theme.

**Comment by agrajaghh** [comment]
I'll have a look at that

**Comment by mcginty** [comment]
@agrajaghh all yours!

**Comment by agrajaghh** [comment]
@mcginty I have a problem finding the svg's for the emoji categories. I have to create a lighter version. Where did you get them from?

![ic_emoji_objects_activated_light](https://cloud.githubusercontent.com/assets/5296073/8004981/1f52c8da-0b85-11e5-93a7-98e3dffe517a.png) etc.
(https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-xxhdpi/ic_emoji_objects_activated_light.png)

**Comment by 2-4601** [comment]
@agrajaghh There's some discussion on the sources in [⌗3316](http://bit.ly/1HPF8yc) (bit.ly link as I dont want to spam with references)

**Comment by agrajaghh** [comment]
@2-4601 I saw that, but there are just the emojis and not the images for the categories (unless I missed something)

**Comment by wp9015362** [comment]
> @agrajaghh wrote:
> 
> @mcginty I have a problem finding the svg's for the emoji categories. I have to create a lighter version. Where did you get them from?

Probably from the stock AOSP Lollipop system keyboard with "Material Light" theme?

They seem to be the same?

The stock AOSP Lollipop system keyboard also has a "Material Dark" theme.

Regards

**Comment by agrajaghh** [comment]
good idea, no svg's but I got high-res png's from the apk (afaik the google keyboard isn't opensource, no?).

**Comment by wp9015362** [comment]
> @agrajaghh wrote:
> 
> no svg's but I got high-res png's

So, it would be possible to use SVGs directly in TextSecure?

Or why were you looking for SVGs instead of PNGs?

I already asked @mcginty if it would be possible to use SVG Emojis directy in TextSecure, see:

https://github.com/WhisperSystems/TextSecure/issues/3316

because the current PNG Emojis have a very low resolution, see:

https://github.com/WhisperSystems/TextSecure/issues/3318

If SVG assets could be used instead of PNG assets, that would be really nice, because SVGs basically can scale to/have an infinite resolution.

Regards

**Comment by agrajaghh** [comment]
@wp9015362 pls stop mixing up different things and mention the same things over and over again, he told you the quality is not perfect because of the performance <-> quality conflict.

to answer your question: no you can't use svgs in android apps directly, but I prefer using svgs if I want to edit the icons to get a better quality (generating png files from the svgs). svgs aren't necessary here because all the icon variants are in the LatinIME repo :)
