### ISSUE TITLE
Initial msg send icon is now paperclip

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3265]
Just updated to 2.16.2.  If I open up a conversation and before I type anything, the send message arrow/airplane is now a paperclip.  It's like this for all conversations.  Is that intended?

**Comment by volcano99** [comment]
Yes, it's intended behavior. That way you can more easily send an attachment. As you start typing the paperclip turns into an arrow

**Comment by jeremymasters** [comment]
I can close this then if @moxie0 or @mcginty chime in officially.

**Comment by volcano99** [comment]
I had a problem a few versions ago which I described here: https://github.com/WhisperSystems/TextSecure/issues/3235. The developers assumed that having a paperclip since the beginning was normal behavior, or they would have probably mentioned it. Also, it makes more sense, doesn't it? Especially now that you can capture photos within the app :)

**Comment by jeremymasters** [comment]
Yeah, it does make more sense.  Who made this silly report anyway? ;)
