### ISSUE TITLE
Contact names missing and pictures flickering on first install

### ISSUE THREAD

**Issue by 5boro** [WhisperSystems/TextSecure#3275]
TS contact of mine sees no contact name, only phone numbers, and pictures are flickering after installing TS for the first time. 
The numbers are in his contacts.

![ts](https://cloud.githubusercontent.com/assets/3460479/7860782/4ce114ee-054c-11e5-923d-be51cdf183a3.jpg)

Log : https://gist.github.com/anonymous/58d83d3af5e75f2cf3c2

**Comment by moxie0** [comment]
Looks like something is pretty fucked up on that device, the contact provider is constantly notifying us of contact changes but not resolving the details.  Does this friend run stock unrooted Android, or are they using xprivacy or some shit like that?

**Comment by 5boro** [comment]
Device is brand new, Huawei flavored android unrooted, so no xprivacy, titanium, or weird stuff.
He absolutely needed TS to communicate, so tried the beta and then went looking for an apk on the web (I know, very bad idea), but strangely he's reporting that v2.6.3 is working fine now.
I'm thinking about building recent versions form source and have him try them out.

**Comment by 2-4601** [comment]
FWI my friend bought a new Huawei phone recently. The ROM that comes in it (stock Huawei) has its own privacy controls and "intelligent" battery optimizations which were on by default. Both features caused issues with TextSecure and had to disabled/whitelisted.

**Comment by 5boro** [comment]
That was it @2-4601, thanks!

**Comment by otosciurus** [comment]
Are you sure you do not want to fix this issue for Huawei devices?

A friend of mine has a Huawei Honor H30-U10. No root, nothing special installed, same contact flickering issue that makes the app barely useable. Whatsapp, Threema, Default SMS app and Telegram seem to find a workaround for the underlying problem. I think any user of a rather recent Android device should be able to run the app in the device's default settings.

I can provide a device log and a video of the issue to someone in private in case you are interested!

**Comment by hrobky** [comment]
I know this is absolute magic, but it solved the flickering problem in my case. 2 of 4 Huawei Ascend p6 phones I know have this problem. It's Android 4.4.2, Emotion UI  2.3, so there is no Permission Manager in the Phone Manager preinstalled app.

**Problem reproduction:**
1. Close Signal using the task switcher. The switcher also closes (without the "has stopped" message), and next click on task switch closes it immediately after start. Second click shows the task switch normally and you don't see Signal among recent apps.
2. Run Signal and see chat list with flickering names/numbers, phone runs slowly and the notifications are not displaying.
3. Open any chat and wait for its name to display. Go back to list, there should be less flickering names...
4. Repeat until there are no flickering names.

At thins point, the problem is still reproducible.

**What I did:**
1. Tried Power Saving: normal; Protected Apps: Signal checked; Re-register Signal messaging (I can confirm - the key doesn't get regenerated even if the application says so); To no avail. Names flickering, notifs not appearing...
2. I turned off/on Manage Apps -> Signal -> Show notifications
3. I turned off/on Signal -> Settings -> Notifications
4. The problem is reproducible just ONCE.
5. I set Power Saving back to Smart; Removed Signal from Protected Apps. This seems not to be the cause.

I re-registered in step 1 because I transfered Signal from other Huawei phone using Huawei Backup (or some other shit, Moxie0 ;)) and I was in doubt, but that was not the cause too. Signal was working few days after the restoration. (IMHO Huawei Backup is preinstalled app with some additional FS rights, so it doesn't require rooting to copy app's data.) This problem might emerge by accidentally disabling notifications.

I don't understand this, but the flickering disappeared, notifications are working again... Even after phone restart.
