### ISSUE TITLE
Add option to mute a conversation indefinitely

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3407]
Currently you can only mute a conversation for a certain period of time (1 hour, 2 hours, 1 day, 7 days).
An option to just turn notifications off indefinitely would be glorious.

btw, what a lovely update this 2.18, so many changes, so shiny, so chrome

**Comment by moxie0** [comment]
Leaving out an indefinite mute was an intentional decision.  I think we'll start this way and see how it goes.

**Comment by kottmann** [comment]
It would be nice to indefinitely mute certain senders, I don't want to block them because sometimes it is interesting to read the messages. For example I constantly get SMS about my phone subscription rate when I cross country borders, or SMS messages from my mailbox.

What was the reasoning behind the decision not to offer indefinite mute?
