### ISSUE TITLE
No updates for device?

### ISSUE THREAD

**Issue by 2011** [WhisperSystems/TextSecure#3418]
I have a bad feeling I am not going to get a friendly response to this. :)

My device (samsung gt-p5113) has TextSecure 2.5.3, which works fine. I recently was looking through the Play Store, and noticed that TextSecure was not listed among my apps. I searched for it, and when I found it, the app page said "this version is not compatible with your device."

I checked with some other people, and they had versions up to 2.17.0! Can someone explain why newer versions are "not compatible," and (I hope) change something so that I am able to install newer versions, and keep up with development.

Thanks.

**Comment by moxie0** [comment]
Looks like a tablet? TextSecure has never supported tablets.  Not sure how you got it on there, but the play store should never have let you install it.  Unfortunately there have been many protocol changes since then, so it'll eventually stop working.

**Comment by 2011** [comment]
@moxie0  Recently came across [Market Helper](http://codekiem.com/2013/02/13/market-helper/) to overcome policies such as this.

I don't understand your hostility towards tablets. Good messaging systems are needed on tablets even more than they are needed on phones.

**Comment by ChaoticMind** [comment]
@2011 It's not a question of hostility, it just hasn't yet been implemented since time is a limited resource (there are 400+ issues open after all).
Tablet support is not trivial since TextSecure uses the phone number as identity, and not all tablets support sim cards. There is, however, progress towards support of multiple devices. Browsers will come first, and tablets might possibly follow a [long?] while after. There is also possibly the question of adapting the UI for larger screens.

If you have further comments about tablet support, you might want to take it to the mailing list since this would no longer be within the scope of a bug report.
