### ISSUE TITLE
Offline group messages arrive out of order

### ISSUE THREAD

**Issue by gartenriese2** [WhisperSystems/TextSecure#3618]
when I turn my internet on and lots of new messages are coming in, they are not shown in chronological order. 
I am using Android 2.3.7

**Comment by moxie0** [comment]
can't reproduce, they're shown the order they were delivered

**Comment by gartenriese2** [comment]
Here is a picture showing the chronological inconsistency: 
![screenshot-1436645275308](https://cloud.githubusercontent.com/assets/4339033/8635214/c0728a60-2819-11e5-96c4-e76bf7ea2ab5.png)

**Comment by wp9015362** [comment]
I am also affected by this issue.

But your issue pretty much is a duplicate, because there is already an open issue for it, see:

https://github.com/WhisperSystems/TextSecure/issues/2385

And today another similar issue popped up, see:

https://github.com/WhisperSystems/TextSecure/issues/3619

Regards

**Comment by gartenriese2** [comment]
Okay thanks! Sorry for the duplicate.
