### ISSUE TITLE
"Camera unavailable" when pressing near emoji/keyboard switcher

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/TextSecure#3629]
Easiest way to do this is to add a couple of lines in the message with the enter key and press the space above, but it works all around the icon.

![emoji](https://cloud.githubusercontent.com/assets/1025490/8637697/a58f3046-289f-11e5-906a-f4d6ff02eb85.png)

**Comment by 2-4601** [comment]
Confirmed on Nexus 4, stock 5.1.1, TS 2.22.0.

**Comment by unrulygnu** [comment]
I ran into this earlier today, as well:

Left side, "Camera unavailable"
![tap-left-kbd-open](https://cloud.githubusercontent.com/assets/11031903/8638131/7efcca14-28eb-11e5-814f-0c2d30ad6004.png)

Right side, launches camera preview (!)
![tap-right-kbd-open](https://cloud.githubusercontent.com/assets/11031903/8638132/83852e32-28eb-11e5-8a86-986abe82562a.png)

Although the `quick_attachment_toggle` was set to `GONE` in a44a4bc, `quick_camera_controls*` are still inflated programmatically:

`src/org/thoughtcrime/securesms/components/camera/QuickAttachmentDrawer.java`

      private void updateControlsView() {
        int controlsIndex = indexOfChild(controls);
        if (controlsIndex > -1) removeView(controls);
        controls = LayoutInflater.from(getContext()).inflate(isLandscape() ? R.layout.quick_camera_controls_land
                                                                           : R.layout.quick_camera_controls,
                                                             this, false);
        shutterButton    = (ImageButton) controls.findViewById(R.id.shutter_button);
        swapCameraButton = (ImageButton) controls.findViewById(R.id.swap_camera_button);
        fullScreenButton = (ImageButton) controls.findViewById(R.id.fullscreen_button);

Commenting out the contents of `updateControlsView()` resulted in NPE's due to the buttons still being referenced elsewhere.  Appending the following code at the end of the method as a temporary workaround is working well so far, but it needs further testing:

        if (!isOpen()) {
          shutterButton.setVisibility(GONE);
          swapCameraButton.setVisibility(GONE);
          fullScreenButton.setVisibility(GONE);
        }
