### ISSUE TITLE
Official Apple emoji discussion forum

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3662]
Apple emojis suck!

> @2-4601 wrote:
> Apple emojis suck!

No, u r wrong, IMHO Google noto emojis suck IMHO

> @2-4601 wrote:
> No, u r wrong, IMHO Google noto emojis suck IMHO

OMG, why don't you just let us CHOOSE, open source is all about freedom why u prevent us from choices. It's just a simple option. IMHO both IMHO suck, use emoji one, the cats are really cute!

> @2-4601 wrote:
> OMG, why don't you just let us CHOOSE, open source is all about freedom why u prevent us from choices. It's just a simple option. IMHO both IMHO suck, use emoji one, the cats are really cute!

You are both(?) wrong and I will kill you for it!

**Comment by McLoo** [comment]
and in group name settings (no emoji drawer, but also no replacement)

**Comment by jellium** [comment]
Why on earth did you switch to Apple emojis?!

**Comment by 2-4601** [comment]
You have now asked this in four different issues and sent email notifications to the participants in all of them.

**Comment by jellium** [comment]
@2-4601 
Please apologize for these overwhelming messages.
I have seen many open issues regarding this and chose to participate to the discussions. However, I haven't sent any email notifications to the participants, Github did.

**Comment by wp9015362** [comment]
@jellium wrote:

I am going to answer your questions here instead of spreading them across several issues.

> @jellium wrote in https://github.com/WhisperSystems/TextSecure/issues/3555#issuecomment-121873682:
> 
> @wp9015362
> 
> why is TextSecure's "Emoji experience" good and native Android's "Emoji experience" bad, IYHO?

IMHO the native Android Emoji experience is bad because it is very inconsistent.

HTC Android devices are using their own HTC Emoji set, Samsung Android devices are using their own Samsung Emoji set, LG Android devices are using their own LG Emoji set, Google Android devices (Nexus) are using their own Google Emoji set and so on...

Everyone sees different Emojis. That just sucks. Especially because of the issue which is described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

In TextSecure however, all the users are seeing the same Emojis, which makes for a much better Emoji experience.

> @jellium wrote in https://github.com/WhisperSystems/TextSecure/issues/3445#issuecomment-121871752:
> 
> And also it is not true that TextSecure makes sure that the Emojis seen on emitter and recipient phones are the same. Just tried with 2.22.2 version to my lady who didn't update: she sees the Google Emojis while I have the ugly Apple ones. 

That is your fault. If you are using 2.22.2 at the moment, then you are on the beta release channel, since 2.22.2 has not yet been released to the stable release channel.

Your "lady" probably is using the stable release channel though, which means she is still using 2.21.0, which means she has not yet been updated to the new Emojis.

Once she will update to 2.22.x, she will see the same Emojis that you are seeing.

So, it's not TextSecure's fault. It's yours (because you are using a beta version).

> @jellium wrote in https://github.com/WhisperSystems/TextSecure/issues/3662#issuecomment-121870421:
> 
> Why on earth did you switch to Apple emojis?!

Well, I can not speak for the TextSecure developers, but:

IMHO the Google "Noto Color Emoji" Emoji set looks like shi*.

Let's face it, most people (or at least a lot), do not like the Google "Noto Color Emoji" Emoji set.

If you don't believe me, then maybe you should read the comments in the following two issues on the AOSP issue tracker:

https://code.google.com/p/android/issues/detail?id=69755
https://code.google.com/p/android/issues/detail?id=73248

And maybe you should also read the comments in the following XDA-Developers forum thread:

http://forum.xda-developers.com/showthread.php?t=2722892

The Apple Emoji set looks a heck of a lot better and is much more popular than the Google "Noto Color Emoji" Emoji set.

The Apple Emoji set is being used in Telegram, ICQ, WhatsApp and so on... (just to name a few examples)

And even the Twitter "Twemoji" Emoji set and the Emoji One Emoji set clearly are modelled after the Apple Emoji set.

So, it's quite popular and therefore pretty much is the natural choice.

Also, Signal-iOS (the iOS counterpart to TextSecure) of course uses the Apple Emoji set, since all iOS devices are using it natively.

So, now that TextSecure for Android also uses the Apple Emoji set, the Emoji experience is much more consistent across both platforms, which lessens the risk of Emojis getting lost in translation as described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

Regards

**Comment by wp9015362** [comment]
PS:

Pardon, 2.22.2 actually has been released on the stable release channel now.

But, anyway:

> @jellium wrote in https://github.com/WhisperSystems/TextSecure/issues/3445#issuecomment-121871752:
> 
> And also it is not true that TextSecure makes sure that the Emojis seen on emitter and recipient phones are the same. Just tried with 2.22.2 version to my lady who didn't update: she sees the Google Emojis while I have the ugly Apple ones. 

then it's still not TextSecure's fault. Just tell your "lady" to update to 2.22.2 and both of you will see the same Emojis.

Regards

**Comment by johanw666** [comment]
Are these Apple emojis freely usable in other programs? I get different opinions when I search about it, and this is also one of the reasons the TextSecure fork SMSSecure didn't make the switch.

**Comment by ncruces** [comment]
That emojis have a semantic meaning and pictorial representation dependent on the font is the whole point of having emoji in Unicode.

A lady in the Huffington Post being afraid of being considered a Playboy bunny who gets around, is neither here nor there, particluarly when it's often Apple that deviates the most from the standard. Consistently bad is the wrong kind of consistency.

Also, speaking of consisfency: should I stop using TextSecure for SMS because 90% of what I get is SMS from Android/Windows that still use other fonts?

**Comment by wp9015362** [comment]
> @ncruces wrote:
> 
> Also, speaking of consisfency: should I stop using TextSecure for SMS because 90% of what I get is SMS from Android/Windows that still use other fonts?

Well, I don't use TextSecure for SMS. If I were to decide, SMS would be removed from TextSecure entirely. So, I don't really care about SMS.

By the way, in the meantime someone opened a issue where your concerns would be more on-topic...:

https://github.com/WhisperSystems/TextSecure/issues/3675

Regards

**Comment by ncruces** [comment]
If it were up to you. And what have you ever done for this community besides saying Google emoji set "looks like #%/!$"?

**Comment by JoeJJJoe** [comment]
Let's appleify everything so we don't have to read articles of random journalists who think everything has to look like it does on her iphone. Oh yeah... what a great improvement.

Anyway, give the user a choice to switch back. Is that too much to ask?
