### ISSUE TITLE
Can't send encrypted messages (after update to 2.22.2)

### ISSUE THREAD

**Issue by duelle** [WhisperSystems/TextSecure#3678]
After I updated to 2.22.2 I seem not to be able to send encrypted messages anymore.
The messages is "pending" for some time and then reports an error: "Failed to send".
The debug log can be found here: https://gist.github.com/anonymous/4c2a87acaf9b65b1de95

Sending "normal SMS" messages seems to work though.
Restarting the phone did not help.

Android : 4.4.2
TextSecure: 2.22.2
Phone: Samsung Galaxy S4 mini

EDIT: Encrypted messaging worked for me some time after the upgrade. Since about 20 minutes it stopped working though.

**Comment by merkste** [comment]
It fails for me too with the same symptoms.https://gist.github.com/c9679381d782636521af

**Comment by DallasO** [comment]
Same here. "Failed to send" almost instantly (on Wi-Fi and on 4GLTE). Can't even "End Secure Session" to by-pass it until it's fixed (same message). TextSecure 2.22.2 - Phone HTC One M8 - Android 5.0.1

Please release A beta candidate so us power users can test updates before they go out - I rely on this app every day and am disappointed at how many times it gets broken. 

(Also, thanks for adding the version number on the app, it was annoying having to go to the App Manager - Not sure when this was added)

**Comment by skulumani** [comment]
Another failure to send here. 

Am also unable to re-register to push. There's a "error connecting to server"

https://gist.github.com/anonymous/9e97c132d5cc1c9250f1

Running TS 2.22.2 on a Moto X 4.4.4
Fails on both 4G and Wifi.

**Comment by merkste** [comment]
Server error? Rebooting the phone does not work either.

**Comment by mattfloat** [comment]
I can confirm the issue is not only on 2.22.2; looks like a server error.

**Comment by McLoo** [comment]
@merkste yes, it's something on the server side. 

So relax and wait for magical server self healing or until Moxie finished his breakfast :bread: :egg: :coffee:

**Comment by TimBo93** [comment]
It's not a support forum , but same here
https://gist.github.com/133a84e852ab188926e6

**Comment by wrdixon** [comment]
Same here.  I can send regular texts, but no encrypted texts.

Moto G 4.4.4, TS 2.22.2
Fails on both 4G and WiFi as well.

I also agree that having a beta channel would be very nice.  I evangelize pretty hard for TS and do fairly well, but people uninstall it really quickly when it stops sending texts.  I've seen two rounds now where 4-5 friends dropped it after delivery issues and it was impossible to get them back on after the problem was resolved.

**Comment by oaim** [comment]
Is this about certificates again? lol
Seriously, textsecure can't become a serious alternate messenger if problems like these still arise... :sad:

**Comment by 2-4601** [comment]
It's probably just karma for the stupidshitemojitrollingspam that infested this place.

**Comment by frozenfoxx** [comment]
Same issue here with 5.1.1 Android.  I love TextSecure but have a hard time recommending it to people due to issues like this cropping up so often in the same way I wouldn't recommend a phone that has an issue making calls.  Is there a way for us to do a "stable" and "beta" branch in the Play store so this kind of thing happens less often?  It'll make it a much easier sell on people for basic messaging.

**Comment by moxie0** [comment]
fixed

**Comment by duelle** [comment]
Thank you.

**Comment by oaim** [comment]
There already is a beta channel, but this issue was server-side, so...

**Comment by merkste** [comment]
Thanks a lot!

**Comment by TimBo93** [comment]
Thank you !

**Comment by karlhedderich** [comment]
thanks :)

**Comment by frozenfoxx** [comment]
Thank you!
