### ISSUE TITLE
Half/full screen button confused on orientation change 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3697]
- Open quick capture in portrait 
- Rotate to landscape 
- see 'toggle full-screen' button instead of the close arrow 
- rotate to portrait, now in full screen, with toggle button indicating you're in half screen

**Comment by 2-4601** [comment]
Step three is different on Nexus 4, stock 5.1.1, TS 23.3.0 (from Play Store): I see the close arrow

- Open quick capture in portrait
- Rotate to landscape
- see the close arrow (no issue here)
- rotate to portrait, now in full screen, with toggle button indicating you're in half screen
- rotate to landscape again
- see 'toggle full-screen' button instead of the close arrow

**Comment by McLoo** [comment]
@2-4601 right you are! Wrote down from memory, while camera was dead 😰

**Comment by McLoo** [comment]
Swipe up in landscape brings back the back arrow
