### ISSUE TITLE
Different Emoji sets when using keyboard button vs textsecure button

### ISSUE THREAD

**Issue by seppi91** [WhisperSystems/TextSecure#3722]
When there's an option in your used keyboard to open an emoji drawer (see pic3), then it uses the default system Emojis (Android - see pic1). When Pressing on the Emoji button of Textsecure at the left side of the TextEntryBox, then it uses the the TextSecure/Apple emojis (pic2).

I think this breaks consistency in the user interaction and should be adressed.

![screenshot_2015-07-19-11-38-12](https://cloud.githubusercontent.com/assets/4396900/8765417/381ab1e0-2e0b-11e5-95b2-e2a7ccdb1209.png)
![screenshot_2015-07-19-11-38-20](https://cloud.githubusercontent.com/assets/4396900/8765416/38195a84-2e0b-11e5-8a04-bf07eaba8a73.png)

![screenshot_2015-07-19-11-38-08](https://cloud.githubusercontent.com/assets/4396900/8765415/381808a0-2e0b-11e5-9c75-621228627aac.png)

**Comment by 2-4601** [comment]
AFAIK applications cannot modify the system keyboard for security reasons. This cannot be done.

**Comment by seppi91** [comment]
So Whatsapp does handle this the same way?
I don't use whatsapp anymore, so can't check it by myself.

**Comment by 2-4601** [comment]
Yes: https://www.reddit.com/r/Android/comments/1uclob/is_there_any_way_to_use_hangouts_emoji_in_other/ceh9mdh

**Comment by seppi91** [comment]
OK. Even if I don't like this behaviour, I think i'll have to deal with it.
Thanks.

**Comment by wp9015362** [comment]
> @2-4601 wrote:
> 
> AFAIK applications cannot modify the system keyboard for security reasons. This cannot be done.

Well, AFAIK, that is not entirely correct. Applications can replace the enter key of the system keyboard with an Emoji key for example. Actually TextSecure had an option to do this a while ago (but the option has been removed now, see https://github.com/mcginty/TextSecure/commit/43e5bc8fd91fa5c287d8c3b48cb949e5b478d3d5).

So, maybe it would also be possible to hide/disable the Emoji key on the system keyboard?

Regards

**Comment by 2-4601** [comment]
Would this then remove the ability to add new lines? And the _enter key sends_ option? Those would be a bad tradeoff.

**Comment by wp9015362** [comment]
> @2-4601 wrote:
> 
> Would this then remove the ability to add new lines? And the enter key sends option? Those would be a bad tradeoff.

I did not say anything about hiding/disabling the enter key on the system keyboard.

I spoke about hiding/disabling the Emoji key on the system keyboard.

Yes, I realize that on a lot of system keyboards, you actually have to press and hold the enter key to see the Emoji key. But maybe it is possible to disable that? So that if you press and hold the enter key, the Emoji key is no longer being offered?

Again, I don't know if this is possible.

But it's definitely possible to replace the enter key on the system keyboard with an Emoji key (I know this because TextSecure actually had an option to do that).

So, who knows, maybe it would also be possible to hide/disable the Emoji key on the system keyboard?

**Comment by Ph1b** [comment]
Something weird happened. When I now press on the smiley icon, very ugly emojis appear. This wasn't the case a version ago. How did this happen?

**Comment by mcginty** [comment]
afaik, there's no way to turn off the emoji keyboard on your IME
