### ISSUE TITLE
MMS size constraints not happy with 1 MB GIFs

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3768]
the one MB limit works fine, except for the case when you switch to MMS and send.
There you'll get a UndeliverableMessageException cause of the dissatisfying size constraints.

*cool, gif finally - so we can use the surfing feature again :surfer:*

**Comment by mcginty** [comment]
Yeah, I started looking into making the constraints a bit smarter. I'm guessing it should be more along the lines of
* If you try and attach media and the recipient is push, check against push constraints. If you override transport to MMS afterwards, fail when hitting the send button instead of inserting a failed message into the convo.
* If you try and attach with MMS, fail immediately if constraints aren't met (draft attachment never shows up in conversation).

**Comment by McLoo** [comment]
@mcginty that's the behavior I had expected - that way were open to (more*) sane audio/video file size

* I know that the auto-non-wifi-download has to be managed first

**Comment by mcginty** [comment]
moving to 2.26.0 since download controls is moving there as well

**Comment by pgnd** [comment]
Any chance of having option to downsize image to within allowed size?

**Comment by mcginty** [comment]
@pgnd there's no easy way to resize gifs on android afaik

**Comment by pgnd** [comment]
'easy' may be the issue ... perhaps these provide some options?

https://developer.android.com/samples/DisplayingBitmaps/src/com.example.android.displayingbitmaps/util/ImageResizer.html
https://github.com/svenkapudija/Android-ImageResizer
https://github.com/bearstouch/android_img_resizer

**Comment by mcginty** [comment]
fixed in 2.27.0 (https://github.com/WhisperSystems/TextSecure/commit/8a1428e7d17aa56a70bdad6b9cd90ee3ce1ed83e)
