### ISSUE TITLE
Deliver a full and a small TextSecure version for enhanced trust

### ISSUE THREAD

**Issue by rschwietzke** [WhisperSystems/TextSecure#3781]
Not everyone wants to use all the features, but the standard install now asks for calendar, microphone (in RedPhone preparation), location, and other permissions. How about a second smaller TextSecure version that really is just a limited secure messenger? Should not even be able to take pictures. Even though it is Open Source and I could check things, most people cannot and hence less Android permissions would create more trust.

Please consider two builds, one full featured and one with just messaging capabilities. You might even kill SMS support and make it even less requiring.

Thanks.

**Comment by Dyras** [comment]
I don't think this is going to happen. I think the whole point of a chat program is to make sure everyone has the same features.

**Comment by ncruces** [comment]
Step one: design a federated protocol and support SMS.

Step two: canned nonsense about ensuring everyone has the same features, down to being able to see the same ugly emoji everywhere.

Makes perfect sense, given it's clearly impossible to do both.

Also, RedPhone never needed to have GPS access, or WiF status. Messaging apps make do without calendar and camera access.

You can certainly take pictures and create calendar events on Android without those. That's the whole point of Android's architecture, which all of the sudden is something WhisperSystems dislikes.

This update is basically "lets ask for everything we can think of", because from experience users don't (auto)upgrade when there are permission changes. Well, good luck with that.

**Comment by johanw666** [comment]
They probably want to include the option to send one's location, like WhatsApp, Viber and others have. Or sending calendar appointments directly to the calendar.

If you want a light version, the best option would be to build TS 2.6.4 from source after removing the expire option (quick hack: make isBuildFresh() in Util.java always return true). Unless the servers stop working with that version of course - keeping track of who's able to cope with encrypted sms has already been removd from the server source.

**Comment by ncruces** [comment]
This is an internet connected app that now asks for more permissions than even Chrome, except Google spends enormous effort hardening Chrome, paying hefty sums to security researchers to find bugs, etc.

A "maliciously crafted" JPEG now has one less layer to bypass before accessing the camera, mic, calendar, location, etc. This, when Android has a perfectly valid intent system for taking pictures, adding events, etc.

But let's every app reinvent picture taking, calendar access, etc, because that's the iOS way. Let's all grow the code base, and the attack surface.

**Comment by turtlekiosk** [comment]
You hit this button: 
![screen shot 2015-07-24 at 11 01 02 am](https://cloud.githubusercontent.com/assets/1096636/8877428/71b894e4-31f3-11e5-9e3a-5be5ed630289.png)
when you probably meant to hit this button:
![screen shot 2015-07-24 at 11 00 55 am](https://cloud.githubusercontent.com/assets/1096636/8877434/7a136f60-31f3-11e5-822a-cafeb9c4db6c.png)

**Comment by rschwietzke** [comment]
@turtlekiosk This does not really help. A landscape full of forks does not really contribute to the overall cause. The name TextSecure stands for something. So why not use it for something simple and something large at the same time. If I need a lot, I use the big one, if I want to have as much security and comfortability, I use the small messenger only.

**Comment by turtlekiosk** [comment]
"A landscape full of forks does not really contribute to the overall cause."
"How about a second smaller TextSecure version that really is just a limited secure messenger?"
- the same person

**Comment by turtlekiosk** [comment]
Honestly, the solution here is using the new runtime permissions in Android M, and not splitting engineering/support efforts on two projects.

**Comment by rschwietzke** [comment]
Yes, but Android M is not available yet, will not be available for everyone, and the average Joe does not have any idea what all of that is, hence more secure by default would be awesome.

If the software is built right, the build job should be able to produce releases in two flavours. The transport layer and the security piece is the same, the stuff on top is different.

If the transport and server layer would be separate, once could build on top of it and possibly fork older version or maintain something with less features.

Just my two cents.

**Comment by moxie0** [comment]
lol, @turtlekiosk can you just be our official spokesperson from now on?

@ncruces Permissions are about protecting users from the app, not about protecting the app from attackers.  This is an open source project, and anyone can verify that we're not using these permissions inappropriately.  If you don't like the features, you're free to not use them.  It sounds as if you don't like the project as a whole, in which case I'm not sure that I understand why you're even posting here.
