### ISSUE TITLE
Can't send any messages

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3834]
https://gist.github.com/760e2ed91a7c15c0e503

**Comment by karlhedderich** [comment]
I also can't send any messages.

**Comment by piratenpanda** [comment]
Same here

**Comment by oaim** [comment]
Same thing happened last week... is there a reason for this? Textsecure is becoming pretty unreliable :/

**Comment by voidzero** [comment]
Same. Sigh.

**Comment by karlhedderich** [comment]
https://gist.github.com/ef942bdda258fc6af289

**Comment by sweah** [comment]
Same here..

**Comment by karlhedderich** [comment]
Agreed, I am trying to get my whole hospital to accept textsecure as the official and mandatory texting app for patient data.  I am afraid these outages are going to make the deciding committee decided against it

**Comment by kevin-george** [comment]
https://gist.github.com/anonymous/cca89c9f74cf9c46dd00

**Comment by voidzero** [comment]
https://gist.github.com/anonymous/2cd323bdb8c547c0ca7c

**Comment by tinloaf** [comment]
Calm down.. this looks like a server blooper which will probably be gone within 20 minutes or so. No need to spam this issue. ;)

**Comment by oaim** [comment]
@tinloaf this problem has been around for at least 35 minutes already... the question is, what's up with the servers recently?

**Comment by Dyras** [comment]
Same here. Seems to be working now though!

**Comment by oaim** [comment]
Resumed working here too

**Comment by Dyras** [comment]
This is exactly why messages should resend automatically instead of showing me that ugly red circle whenever the server is down.

**Comment by Dyras** [comment]
Yup, and now it's down again.

**Comment by Dyras** [comment]
oaim just leave this open so that Moxie or whoever sees it.

**Comment by oaim** [comment]
Lol you're right, I guess I'll leave this open for a while

**Comment by danlyke** [comment]
AOL. Here's my log: https://gist.github.com/ca2f6f269e472d258c0e

**Comment by voidzero** [comment]
@tinloaf spam this issue? What do you mean?

**Comment by tinloaf** [comment]
@voidzero 25 People posting 'Same here' is not very useful. Also, if you look at the debug logs, they all contain the same. Basically posting here any more messages will not make the issue go away any sooner, it will just mean that the devs will have to click away more mails and sort through more noise.

**Comment by voidzero** [comment]
@tinloaf there is some value for some users to have posted it, to get it off their chest. That's not spamming. Useful for the developers, maybe not. Useful to some users, maybe so. Let's not tell 'em to shut up, eh? Let's assume they know what you say already, and still want to post this. Let's act like we're cool with that, because we know how these things work and we can unsubscribe to their notifications. And because the alternative is more hostile and that might cause getting less feedback with other issues.

**Comment by Dyras** [comment]
People writing that it's down for them gives the developers a picture of who has problems and who hasn't. If 2 people posted here then it would be easy to say it's their connection. When 25 people show up that is obviously not the case. I live in Sweden and I had issues, which is why I came here. A friend of mine on the other hand had no such issues, and she lives an hour away from me which at first made me believe it's my phone acting up.

**Comment by kevin-george** [comment]
I'm no longer seeing the EOFException in the logs, but the messages aren't being delivered either.

**Comment by oaim** [comment]
Your friends probably need to open textsecure. It works fine for me and my friends
