### ISSUE TITLE
Sending message via TextSecure servers causes app crash

### ISSUE THREAD

**Issue by MostAwesomeDude** [WhisperSystems/TextSecure#3852]
Hi! Debug log is at https://gist.github.com/anonymous/cf13994aa7ab1343066a and hopefully isn't terribly embarrassing.

I sent a friend a single message and got one of the JSON errors in the log. Being stubborn, I tried many more times and got many more errors. Disabling TextSecure servers for messages (forcing the SMS fallback, right?) causes the message to go through, no crash, no problem.

I just updated TS to 2.23.3 and my Android version is 5.0.x on a Nexus 5. Not super-confident of the actual Android version as it was an OEM-provided phone, not purchased through my service provider.

Hope this helps!

**Comment by moxie0** [comment]
This is a problem that occurs when sending messages to people running "whisperpush," which is Cyanogen's (currently quite outdated) implementation of TextSecure.  The actual crash is already fixed in 2.24.0 (currently in the beta channel), but I should be able to figure out how to patch things up on the server side for 2.23.0 users.

@MostAwesomeDude I don't currently have any way to reproduce this. Do you think your friend would be willing to provide me with their phone number so that I can debug by sending messages to them?

**Comment by MostAwesomeDude** [comment]
The friend in question stopped using CM some time ago; I suppose that the bug was provoked by an older message which had been trying to arrive. I'm sorry that I cannot help with reproduction. Thanks again for a wonderful application and speedy triage. Peace.
