### ISSUE TITLE
End Secure Session doesn't work

### ISSUE THREAD

**Issue by DallasO** [WhisperSystems/TextSecure#3858]
I am on a thread, clicking the 'lock' symbol on top, and selecting 'End secure session'. The auto generated message 'Secure session ended.' is sent and received(have message receipt request turned on, 2 check marks). Next message either sent or received is still secured!(has lock symbol on message). Have tried multiple times now. 

Would prefer not un-registering from the TS server just to text someone who is wanting to uninstall TS (unrelated problem with keyboard not liking TS)

HTC One M8
TS 2.23.3
Android 5.0.1

**Comment by moxie0** [comment]
*Sigh*.  Please try searching existing issues before opening new ones, and please see http://support.whispersystems.org for support rather than posting here.

This is the intended behavior.  If you want to send your friend an insecure SMS and TextSecure is your default SMS app, you can long-press on the send icon to select insecure SMS.  You should also ask your friend to unregister from TextSecure here: https://whispersystems.org/textsecure/unregister
