### ISSUE TITLE
Most Required Features 

### ISSUE THREAD

**Issue by Ravray** [WhisperSystems/TextSecure#3953]
This is my first post. 
I just compared textsecure with whatsapp and found that many features is required. 
Hereby i try to list the most required features. 
Audio call
Brodcast
Profile Pic
Status
Last seen
Typing
Wallpapper or Custom Background 
Email Chat
Location Share
Delete Account
Change Number
Optiin to Auto download media

I just mentioned above features after comparison with whatsapp. Its not necessary that we build application like whatsapp but above mentioned features is required for any messenger application. 
I also found some issue in ts. 
Like if you add any friends in group after that admin can not remove any friends from the group. Admin must remove any member from group. 
When some members post text message in group then notification shows that this friends post text message but does not show the group name, so we think that this is private message but actually its group message. 
Other issue is we only select one image at time, we must select 10 to 20 image at time. 
Sorry for my bad English but i tried to contribute to this awesome app. 
Thanks 
Bahadursinh

**Comment by johanw666** [comment]
TextSecure is not WhatsApp. Having said that:

Status is hardly ever used in WhatsApp. Last seen and typing are privacy risks, even when WhatsApp intruduced them they were controversial. Audio call is being worked on by integrating Redphone (for now, download Redphone as a separate program). Judging from the new permissions location sharing is in the planning. Delete account and change number is already working, just unregister, and if you have a new number re-register.

Groups work inherrently different in TextSecure because all group data is stored locally and not on a central server, like WhatsApp does. Storing it centrally would increase the risk of secret requests for the data by the usual 3 letter agencies.

A decent backup function is indeed required, the existing one was removed due to problems but the plaintext backup is only half usefull, it backups only text messages and no identity keys, media or mms messages. Hacking it back in (is not very difficult, the code is commented out and not deleted) or using Titanium Backup usually works, although you might have to re-register because keys might be out of sync.

**Comment by oaim** [comment]
There are already open issues for most (if not all) the features you propose and bugs you report.
Either you close the issue or one of the developers will come and say something like "This is an issue tracker, not a discussion forum. You can use the mailing list to propose features etc etc". I think they're more than aware that TS lacks some features after all the people who've been reporting them in the past... :)

**Comment by Mihahn** [comment]
There are already open issues for most things on your list! 

Audio call: I guess it will come when merging TextSecure and Redphone to Signal
Brodcast: https://github.com/WhisperSystems/TextSecure/issues/3301
Profile Pic: https://github.com/WhisperSystems/TextSecure/issues/916 or https://github.com/WhisperSystems/TextSecure/issues/706
Status: https://github.com/WhisperSystems/TextSecure/issues/2197
Last seen: https://github.com/WhisperSystems/TextSecure/issues/3252
Typing: https://github.com/WhisperSystems/TextSecure/issues/1121
Wallpapper or Custom Background: https://github.com/WhisperSystems/TextSecure/issues/809 
Email Chat
Location Share: https://github.com/WhisperSystems/TextSecure/issues/638
Delete Account: https://whispersystems.org/textsecure/unregister/
Change Number: http://support.whispersystems.org/customer/portal/articles/1468975-what-happens-when-i-change-my-phone-number- or https://github.com/WhisperSystems/TextSecure/issues/3558
Optiin to Auto download media: https://github.com/WhisperSystems/TextSecure/issues/721 or https://github.com/WhisperSystems/TextSecure/issues/930

Please check existing issues before opening new ones :wink:
