### ISSUE TITLE
Warn users before build expiration lockout

### ISSUE THREAD

**Issue by mildmojo** [WhisperSystems/TextSecure#4046]
My copy of TextSecure 2.6.4 started refusing to send plaintext SMS today. It turns out the build has "expired" for some value of "expired". This was surprising and frustrating.

I checked the mailing list, issues, and Google for any information about build expiration or the "Your build of TextSecure has expired!" message, but the only references I found were in the source code in this repo.

Please either remove this expiration or warn about it weeks ahead of the actual date. And perhaps display the expiration date in the app's settings and/or document the expiration window online somewhere. Maybe in the repo's README or the Google Play description.

**Comment by jeremymasters** [comment]
I know expiration won't be removed because it becomes difficult to support so many old versions from both the client and server API codebases.  You should think about updating to the latest version to enjoy all the new features as you are about 20 releases behind.  If encrypted SMS is what you're after, there is always SMSsecure.

**Comment by mildmojo** [comment]
Thanks for the [SMSSecure](https://smssecure.org/) pointer! That looks perfect, and I'll probably migrate to that. I stopped updating TextSecure when I heard secure SMS support was going to be dropped.

I still think it's worth documenting and warning about the expiration behavior, though. Like Windows updates, this sort of thing tends to crop up at the worst possible time.
