### ISSUE TITLE
Requesting userAgent mod or option in TextSecure settings

### ISSUE THREAD

**Issue by mjoelner** [WhisperSystems/TextSecure#466]
First off let me thank you for a great app.

I am using an unlocked phone on the SoftBank network in Japan.  The SoftBank mms server checks the userAgent field to make sure it matches phones sold by SoftBank.

It would be great if Textsecure could either add the res/xml-mcc440-mnc20/ folder with all files from the xml folder but with mms_config.xml modified as described here:
http://lazydroid.com/2012/04/howto-send-and-receive-mms-on-galaxy-nexus-softbank/
and here
http://forum.xda-developers.com/showthread.php?t=2451413

Or allow users to input userAgent as an option in settings.  I believe GO SMS Pro has this function but I would prefer something with better security.

I have tried to make the edits myself but am getting recompile errors.  I will keep trying but I am sure many more would benefit form such as option.

**Comment by SamWhited** [comment]
I added this as a preference (the idea of maintaining resources for different providers who restrict what phones you can use this way wearies me) and opened a pull request, but there are a few things I wouldn't mind feedback on:

While I don't like the idea of maintaining provider specific resources, I also don't like the idea of every random user having access to this sort of thing and messing with it. There are other advanced options like this in TextSecure, but they're generally hidden away. Would this be better in advanced options (instead of SMS & MMS options), or maybe in a separate sub-category inside SMS & MMS options like the advanced MMS options (with a check box to turn them on)? It felt silly to add one for a single SMS preference, but that may be the best way. Let me know and I'll update the pull.

Secondly, the default behavior should probably be that if the user "empties" the edit text and saves the preference as an empty string, it goes back to the default (unless we use the checkbox / subcategory idea above). It doesn't look like the other similar preferences do this (they're just regular edit preferences), but would this be something that might be good to implement (I suspect it would be useful elsewhere)?

**Comment by agrajaghh** [comment]
fixed in https://github.com/WhisperSystems/TextSecure/commit/dbda7588419a351d24f4df4ee660f02626471a0b, no?
