### ISSUE TITLE
MMS doesn't seem to work

### ISSUE THREAD

**Issue by frioux** [WhisperSystems/TextSecure#511]
I'm not really sure what is going on, and it may be a problem with my phone.  Basically we have a Moto-X on the AT&T network.  MMS seems to work with the stock Messaging App, but in TextSecure it never seems to connect to the MMS server to download the attached image.

I've tried setting the MMS server info but I could be doing that wrong.

On a related note, I think it would be handy if I could use the standard app for MMS but TextSecure for SMS.  I think there are some issues with automatically shrinking images for MMS as well that might be tougher to fix.

**Comment by rhodey** [comment]
this issue is crazy old and our MMS code has changed many times over since, unfortunately all information in this issue is stale & cannot benefit us in improving MMS further. if anyone in this thread is still having issues with MMS please find a recent issue that matches your behavior and preferably network provider and add a debug log there.
