### ISSUE TITLE
Feature request: Disable MMS sending

### ISSUE THREAD

**Issue by fadenb** [WhisperSystems/TextSecure#769]
Using the groupchat feature yesterday I added 2 contacts and did *not* get the warning that they do not support the data channel (actually we were using the data channel before without problems). I sent a message to the group and it was sent out as MMS.

Since MMS are disproportionately priced with my mobile plan I would love to **disable MMS completely**.

Would entering gibberish settings in the manual MMS configuration dialog be a working workaround for this until this request ist decided/implemented?

**Comment by kappapiana** [comment]
Yes, **why the hell** is this still an option? It should be disabled **by default** and enabled only after one confirms they are mentally sane. Which is sort of catch 22, because you must be insane to send out SMS. This costed me 14 euro. **WTF**

**Comment by u32i64** [comment]
@kappapiana it will probably sound strange to you, as it is to me, however in some countries MMS is usually included with SMS and so they have no problem with Signal sending MMS, [e.g. in the US](https://community.signalusers.org/t/import-system-mms-database-into-signal/3977/11?u=u32i64).

**Comment by kappapiana** [comment]
I understand. However, since it is a substantial problem for a non
negligible market as 500M people on this side of the Ocean, why not
making it at least an opt-out option? I have reactivated the SMS
application and disabled Signal for non-secure communication, which is a
very sad decision, considering that Messages is a Google application and
it would make my SMS possibly visible to Google not just via NSA.

Cheers

Carlo
